### ISSUE TITLE
[license] is it ok to redistribute the maxmind mmdb files?

### ISSUE THREAD

**Issue by celevra** [bunkerity/bunkerweb#1093]
### What happened?

under /src/bw/misc
are the ASN and Country mmdb Files from maxmind
are you sure that it is ok to distribute them like this?

### How to reproduce?

^^

### BunkerWeb version

1.5.6

### What integration are you using?

Docker

### Removed private data

- [X] I have removed all private data from the configuration file and the logs

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TheophileDiot** [comment]
Hi @celevra, thank you for opening this issue.
The files present in `src/bw/misc` aren't from **maxmind** but from **db-ip**

sources:
https://db-ip.com/db/download/ip-to-country-lite
https://db-ip.com/db/download/ip-to-asn-lite

**Comment by celevra** [comment]
thank you for clarification
