### ISSUE TITLE
Roadmap / TODO

### ISSUE THREAD

**Issue by fl0ppy-d1sk** [bunkerity/bunkerweb#111]
The current stable version is [v1.3.X](https://github.com/bunkerity/bunkerized-nginx/releases/latest). New features will be integrated if they don't break backward compatibility otherwise they will be delayed to the next version.

Feel free to comment if you have any implementation idea or feature request. You can also join our [community chat](https://compiled.social/bunkerity-chat) to talk about it.

TODO list : 

- Features
  - Trusted-Types CSP
  - IPv6 support
  - Improve and document API : ban management, stats, ...
  - Shared DB support like Redis when using Swarm and Kubernetes integrations

- Container
  - Arbitrary user id
  - Alternatives images (e.g. : LibreSSL, mainline, ...)

- Web UI
  - Autoconf support
  - Swarm support
  - Kubernetes support
  - API integration

- Examples
  - Edit Wordpress example
  - Add more details for each integration
  - Add cache volume

- Plugins
  - Refactoring of the LUA logic for security checks and make them as plugins
  - Improvement of the plugin system with full support on all integrations

**Comment by AquaeAtrae** [comment]
Great project. I've offered a pull request ([119](https://github.com/bunkerity/bunkerized-nginx/pull/119)) that I needed and should have more ideas as I dig deeper. I'm a bit new to collaborative development, but can hopefully offer worthwhile feedback and contributions. Thanks @bunkerity

**Comment by bunkerity** [comment]
Hello @AquaeAtrae,

Thanks for your PR. I've added a comment to it.

**Comment by AquaeAtrae** [comment]
@bunkerity The new template-based configurations no longer support the SITE_ROOT_SUBFOLDER feature we previously had working. I commented in the original PR, but I'm not sure that reached you [there](https://github.com/bunkerity/bunkerized-nginx/pull/119#discussion_r650179773). Sorry if I should respond elsewhere; I'm still learning my way around here.

**Comment by bunkerity** [comment]
Hey @AquaeAtrae,

Looks like you have a typo we called it **ROOT_SITE_SUBFOLDER** not **SITE_ROOT_SUBFOLDER**. It's even hardcoded in the generator as you can see [here](https://github.com/bunkerity/bunkerized-nginx/blob/master/gen/Templator.py#L49-L50). I will test it just in case.

**Comment by AquaeAtrae** [comment]
Thanks for the testing @bunkerity,

Yeah, we had noted that earlier ([May 3](https://github.com/bunkerity/bunkerized-nginx/pull/119#discussion_r624932530)) ...and I thought it was fixed. I know it was working correctly when I tested it back then. 

PS: I'm impressed with the new features and documentation. I'd love to see solid default security become highly accessible and easy to implement / maintain for the masses.

**Comment by bunkerity** [comment]
Hey @AquaeAtrae,

Just quickly tested the [multisite-custom-subfolders example](https://github.com/bunkerity/bunkerized-nginx/tree/master/examples/multisite-custom-subfolders) and it works on my side : 
```shell
$ curl -H "Host: app1.website.com" -H "User-Agent: Legit" http://localhost
welcome to app1 !
$ curl -H "Host: app2.website.com" -H "User-Agent: Legit" http://localhost
welcome to app2 !
$ curl -H "Host: app3.website.com" -H "User-Agent: Legit" http://localhost
welcome to app3 !
```
