### ISSUE TITLE
[FEATURE] Is there a way to deploy 2 services as reverse proxy where leaving a one without any protections and just bypassing everything

### ISSUE THREAD

**Issue by sbe-arg** [bunkerity/bunkerweb#1183]
### What's needed and why?

I'm having a lot of problems with nextcloud talk to establish calls and need them working. Would be happy to whitelist nextcloud out of all the other controls for a bit.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TheophileDiot** [comment]
Hi @sbe-arg, yes it is possible with the whitelist IP, you just have to add the IP to the setting `WHITELIST_IP` and all traffic wont be checked by BunkerWeb.
https://docs.bunkerweb.io/1.5.6/settings/#whitelist

**Comment by sbe-arg** [comment]
No I mean whitelist a service not an origin.

For example all traffic going to site1 to not do any checks and just passtrough

**Comment by fl0ppy-d1sk** [comment]
Hello @sbe-arg,

If you use multisite mode with `MULTISITE=yes` setting, you can apply `WHITELIST_IP=0.0.0.0/0` only to a specific service by prefixing with the first server name of the service : `www.example.com_WHITELIST_IP=0.0.0.0/0`.

More info : 
- Multisite concept : https://docs.bunkerweb.io/latest/concepts/#multisite-mode
- Example of prefixing : https://docs.bunkerweb.io/latest/quickstart-guide/#multiple-applications
- Whitelisting : https://docs.bunkerweb.io/latest/security-tuning/#whitelisting

**Comment by sbe-arg** [comment]
Nice
