### ISSUE TITLE
[FEATURE] hardened security on the 401 pages

### ISSUE THREAD

**Issue by sbe-arg** [bunkerity/bunkerweb#1187]
### What's needed and why?

When you have a website that shows the 401 page intentionally at root / 

Mozilla observatory reports the domain as D

![image](https://github.com/bunkerity/bunkerweb/assets/23391642/fe19983e-2a4d-46fb-b733-c887ad74bedf)
![image](https://github.com/bunkerity/bunkerweb/assets/23391642/8fcc7408-1f61-4c6d-82ed-2a0b8e3cda2c)
![image](https://github.com/bunkerity/bunkerweb/assets/23391642/e949d117-a2ad-4818-84ca-9dd8953bfcb5)
![image](https://github.com/bunkerity/bunkerweb/assets/23391642/d8038eaa-df71-4416-b88e-66c02885a384)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TheophileDiot** [comment]
Hi @sbe-arg, thank you for opening this feature request. Did you activated the CORS in the settings by any chance ?
I'll have a look for an hardened CSP on error pages.

**Comment by sbe-arg** [comment]
I'm running cors with the default settings have not made any cors changes.

**Comment by TheophileDiot** [comment]
I added the CSP header for the error pages, thank you again for this feature idea.
For the CORS, this is very weird if you have the default values it shouldn't accept the requests, i'll have a look into it and let you know !
