### ISSUE TITLE
[BUG] Incorrect nginx dependency for Ubuntu Noble package

### ISSUE THREAD

**Issue by vertikel** [bunkerity/bunkerweb#1189]
### What happened?

Tried to install Bunkerweb using the Ubuntu Noble package repository hosted on packagecloud.io.

Downloaded and ran the script from https://packagecloud.io/install/repositories/bunkerity/bunkerweb/script.deb.sh. The repository setup was successful, but the installation failed.

### How to reproduce?

```
root@waf:~# curl -s https://packagecloud.io/install/repositories/bunkerity/bunkerweb/script.deb.sh | bash    
Detected operating system as Ubuntu/noble.
Checking for curl...
Detected curl...
Checking for gpg...
Detected gpg...
Detected apt version as 2.7.14
Running apt-get update... done.
Installing apt-transport-https... done.
Installing /etc/apt/sources.list.d/bunkerity_bunkerweb.list...done.
Importing packagecloud gpg key... Packagecloud gpg key imported to /etc/apt/keyrings/bunkerity_bunkerweb-archive-keyring.gpg
done.
Running apt-get update... done.

The repository is setup! You can now install packages.

root@waf:~# apt-get install bunkerweb=1.5.7
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 bunkerweb : Depends: nginx (= 1.24.0-1~jammy) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

https://packagecloud.io/bunkerity/bunkerweb/packages/ubuntu/noble/bunkerweb_1.5.7_amd64.deb?distro_version_id=284 also lists `nginx (= 1.24.0-1~jammy)` as dependency.

### Configuration file(s) (yaml or .env)

```YAML
root@waf:~# grep '^deb ' /etc/apt/sources.list.d/bunkerity_bunkerweb.list
deb [signed-by=/etc/apt/keyrings/bunkerity_bunkerweb-archive-keyring.gpg] https://packagecloud.io/bunkerity/bunkerweb/ubuntu/ noble main

root@waf:~# grep VERSION= /etc/os-release
VERSION="24.04 LTS (Noble Numbat)"
```

### BunkerWeb version

1.5.7

### What integration are you using?

Linux

### Linux distribution (if applicable)

Ubuntu 24.04 LTS

### Removed private data

- [X] I have removed all private data from the configuration file and the logs

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TheophileDiot** [comment]
Hi @vertikel.This is intended because, as stated in the [documentation](https://docs.bunkerweb.io/1.5.7/integrations/#__tabbed_1_2), "the nginx package is not available in the official repository" of Noble.
