### ISSUE TITLE
[DOC] mod access

### ISSUE THREAD

**Issue by sebstyle** [bunkerity/bunkerweb#1221]
### Description

A question and a suggestion..

It is unclear to me as to what would be the best way to go about implementing basic access control?
- Blacklist 0.0.0.0 & Whitelist or Greylist 192.168.0.0/24
- Custom server-http file with simple allow 192.168.0.0/24; deny all;
- Perhaps using Reverse proxy includes but it is unclear how that works

I just want to enable letsencrypt ssl but allow access from LAN only.

In case of the whitelist module the default value contains a bunch of IP addresses.
The documentation on default values could be a bit more extensive when it comes to these kind of values.
Personally I would want to know who I am granting access (whitelist)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TheophileDiot** [comment]
Hi @sebstyle, I would suggest a combination of the blacklist `0.0.0.0/0` and the whitelist if you trust the traffic in your LAN environment, else the greylist is also a great choice to have the same effect but still execute the security check on requests.
