### ISSUE TITLE
[BUG]  UI config not being overridden by autoconf/scheduler

### ISSUE THREAD

**Issue by cocoonkid** [bunkerity/bunkerweb#1302]
### What happened?

I have set basic auth in bunkerweb docker compose from the .env

![image](https://github.com/bunkerity/bunkerweb/assets/43231640/05b47d3c-5cbf-4987-a3fc-b26eb3d747f6)

 image: bunkerity/bunkerweb:1.5.8
![image](https://github.com/bunkerity/bunkerweb/assets/43231640/34b54df3-2c84-409d-8f3f-d27529ea696a)

and it works. But when I set it in another services like invidious:
![image](https://github.com/bunkerity/bunkerweb/assets/43231640/3ba05a20-44c5-4c60-a747-1cfd00645248)

it still asks for auth.  (EDIT: I fixed the typo there with bunkerweg is now bunkerweb)

I restarted & recreated all containers. 
Also deleted all bunkerweb volumes and fully reinitialized with 1.5.8 but it still does not work as expected.

What could the problem be ?

### How to reproduce?

Set basic auth for multisite. It works as expected. 

set  the following in docker compose of other service as 

```
labels:
	  - "bunkerweb.USE_LIMIT_CONN=no"
      - "bunkerweb.USE_LIMIT_REQ=no"
      - "bunkerweb.USE_ANTIBOT=no"
      - "bunkerweb.USE_AUTH_BASIC=no"
 ```
 
 
 get ignored.

### BunkerWeb version

1.5.8

### What integration are you using?

Docker

### Linux distribution (if applicable)

Ubuntu 24.04

### Removed private data

- [X] I have removed all private data from the configuration file and the logs

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cocoonkid** [comment]
I found the problem. As it looks I had basic auth set in the bunkerweb admin UI. 
I must have done that literally years ago :-)
So I would recommend that a check get's added that will log an Info out like:
```
Basic Auth env var is configured differently from your Bunkerweb UI settings. Please make sure this is what you want. ```

does this make sense ?

**Comment by TheophileDiot** [comment]
Hi @cocoonkid, thank you for opening this issue, I'll have a look and let you know !

**Comment by TheophileDiot** [comment]
I couldn't reproduce the issue, did you restarted your service correctly ?
```shell
docker compose -f myfile.yml down
docker compose -f myfile.yml up```

**Comment by cocoonkid** [comment]
Hi, sorry for taking time to reply.

I found this happens to all 1.5.7 that I updated to 1.5.8. 
The webui settings suddenly overrode the settings from the compose file. 

With 1.5.9 it seems to be ok again. 
Will verify soon and report back.

**Comment by TheophileDiot** [comment]
Hi @cocoonkid, thank you for the update !

**Comment by cocoonkid** [comment]
Yes this seem to be working. Sorry for the late reply.
