### ISSUE TITLE
[BUG] Cannot add more than 3 reverse_proxy in services

### ISSUE THREAD

**Issue by andreaci** [bunkerity/bunkerweb#1385]
### What happened?

Opening a "service" details, adding "reverse proxies" to a service, won't allow to add more than 3

### How to reproduce?

- Create a new service
- select the "reverse proxy" plugin
- in the "multiple settings" area, click on ADD a few times
![image](https://github.com/user-attachments/assets/e261abf8-363a-46b8-bdc0-b3fa1f82ba90)
- with every click, a new "data block" will appear, but the index of each data block will stop at 2:
 
![image](https://github.com/user-attachments/assets/12b0cd0a-984a-42ed-b63b-cb364719e58e)

so, you will have the "Reverse proxy host", "Reverse proxy host 1", "Reverse proxy host 2", "Reverse proxy host 2", "Reverse proxy host 2", "Reverse proxy host 2", "Reverse proxy host 2" 

### BunkerWeb version

1.5.9

### What integration are you using?

Docker

### Removed private data

- [X] I have removed all private data from the configuration file and the logs

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fl0ppy-d1sk** [comment]
Hello @andreaci,

It should be fixed in the last 1.5.10 release. Enjoy !
