### ISSUE TITLE
[BUG] Persistent auto-regeneration of invalid config with double dollar signs ($$) causing Nginx failures

### ISSUE THREAD

**Issue by psychedelicu** [bunkerity/bunkerweb#1399]
### What happened?

I'm experiencing a critical issue where BunkerWeb keeps regenerating a configuration file for auth.domain.com that includes invalid variable references using double dollar signs ($$) instead of a single dollar sign ($). This mistake breaks Nginx every time it attempts to reload.

### How to reproduce?

If I modify or remove the problematic configuration, those changes should persist, and the configuration should not be automatically regenerated incorrectly.

Every time BunkerWeb restarts, the same invalid configuration is regenerated, making it impossible to permanently fix the issue. This forces me to reinstall the entire BunkerWeb container and instance to restore functionality, which is incredibly frustrating. Please fix this!

### BunkerWeb version

1.5.9

### What integration are you using?

Docker

### Linux distribution (if applicable)

Linux

### Removed private data

- [X] I have removed all private data from the configuration file and the logs

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TheophileDiot** [comment]
Hi @psychedelicu, thank you for opening this issue. Do you have any relevant log that may help us understanding what happened ? Thank you

**Comment by TheophileDiot** [comment]
@psychedelicu bump
