### ISSUE TITLE
[FEATURE] Trusted-types

### ISSUE THREAD

**Issue by thelittlefireman** [bunkerity/bunkerweb#141]
**What's needed and why ?**
As a reminder, when all browers will be compatible could it be possible to add the new header trusted-type to prevent xss. 
https://developer.mozilla.org/fr/docs/Web/HTTP/Headers/Content-Security-Policy/require-trusted-types-for&ved=2ahUKEwjZ_fjd-IzxAhUsDmMBHRN4DCEQFjAAegQIBRAC&usg=AOvVaw15mmmIwnAVf_Wy7OJSpKmm

**Implementations ideas (optional)**
Add the new header by default and a endpoint to catch errors https://web.dev/trusted-types/.

Let user could edit the header (enable, disable, force) for multisite

**Comment by fl0ppy-d1sk** [comment]
Hello @thelittlefireman,

Looks like it would be easy to add because it can be enabled with the Content-Security-Policy header. But I'm wondering if it would cause any false positive from common applications like Wordpress or NextCloud. Do you have any thoughts on this ?

**Comment by fl0ppy-d1sk** [comment]
Closing this because we plan to add more features around CSP in BW 1.6.0
