### ISSUE TITLE
[BUG] bunkerweb container sets label "bunkerweb.INSTANCE" to "bunkerweb" instead of "yes" 

### ISSUE THREAD

**Issue by chrismade** [bunkerity/bunkerweb#1410]
### What happened?

I discovered that when starting the bunkerweb container with docker or podman
`podman run  --name testbw2 docker.io/bunkerity/bunkerweb:1.5.9`
a label is already set for bunkerweb.INSTANCE
see
`podman inspect testbw2`
will show in labels section:
```
               "Labels": {
                    "bunkerweb.INSTANCE": "bunkerweb",
                    "bunkerweb.type": "bunkerweb",
```
however, in order to get a working setup the value must be "yes" - I wonder if the preset to 'bunkerweb' was intended to indicate it was not explicitely overwritten by "yes" - or if we could make every bunkerweb users lives easier by rather presetting it to "yes" by default when the container is spun up?? 

### How to reproduce?

`podman run  --name testbw2 docker.io/bunkerity/bunkerweb:1.5.9`
to spin up a container and then very settings incl labels by
`podman inspect testbw2`

### Configuration file(s) (yaml or .env)

```YAML
N/A
```

### Relevant log output

```shell
see above
```

### BunkerWeb version

1.5.9

### What integration are you using?

Docker

### Linux distribution (if applicable)

Fedora 40 (coreos / podman) and debian12 w/docker

### Removed private data

- [X] I have removed all private data from the configuration file and the logs

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TheophileDiot** [comment]
Hi @chrismade, thank you for opening this issue. Indeed there is an already defined label in newer version.
For the value of the label it doesn't really matter as of now, we set it to `yes` as a placeholder.

**Comment by chrismade** [comment]
thanks @TheophileDiot  - pls feel to close then - I already noticed that the existence of that label already does the job no matter of its content - changing the docu might also be ok
