### ISSUE TITLE
[BUG]  can't update cachestore

### ISSUE THREAD

**Issue by celevra** [bunkerity/bunkerweb#1524]
### What happened?

Hi,

we have multiple (every second):
[error] 89138#89138: *1247415 [SET] can't update cachestore : could not poll ipc events: timeout,
and
[error] 89233#89233: *1264652 [SET] whitelist:set() failed : /usr/share/bunkerweb/deps/lib/lua/resty/lock.lua:154: API disabled in the context of set_by_lua*
and
[error] 89224#89224: *1261533 [WHITELIST] error while adding element to cache : could not broadcast update: failed to insert event in shm: no memory

this is docker stats
`
CONTAINER ID   NAME                    CPU %     MEM USAGE / LIMIT     MEM %     NET I/O           BLOCK I/O        PIDS
6a97c7160045   bunker-bw-scheduler-1   0.45%     115.9MiB / 62.59GiB   0.18%     3.85GB / 415MB    3.3MB / 263MB    3
cfafba4ad929   bunker-bw-ui-1          0.48%     2.216GiB / 62.59GiB   3.54%     111kB / 87.5kB    0B / 49.2kB      32
6a59c42da7d4   bunker-bunkerweb-1      0.20%     2.086GiB / 62.59GiB   3.33%     6.69GB / 6.83GB   1.2MB / 2.3GB    34
0d9d8232197a   bunker-bw-db-1          0.12%     940.2MiB / 62.59GiB   1.47%     145MB / 3.79GB    231MB / 90.8MB   11
b37737b99ece   bunker-bw-docker-1      0.14%     7.094MiB / 62.59GiB   0.01%     3.04MB / 60.9MB   0B / 36.9kB      33
`

### How to reproduce?

i have no glue

### BunkerWeb version

1.5.10

### What integration are you using?

Docker

### Removed private data

- [X] I have removed all private data from the configuration file and the logs

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TheophileDiot** [comment]
Hi, could you provide us with a bit more information about your use case, stack, integration, etc... ? Thank you
