### ISSUE TITLE
[BUG] Nginx spam log about `upstream server temporarily disable` and `connection refused`

### ISSUE THREAD

**Issue by thelittlefireman** [bunkerity/bunkerweb#157]
**Description**
Since 1.2.7, nginx spam in logs about `upstream server temporarily disable` and `connection refused` on all of my subdomain. Everything is working find. I think it something about IPV6 listen port(all logs are about `http://[::1]:XX`). I only use IPv4 on my server. Is there something we can do about this ?

**How to reproduce**
Just add a subdomain and disable ipv6 on server.

**Logs**
```
2021/07/15 15:12:54 [error] 574#574: *202525 connect() failed (111: Connection refused) while connecting to upstream, client: X.X.X.X, server: gitlab.mydomain, request: "POST /api/v4/jobs/request HTTP/1.1", upstream: "http://[::1]:XXX/api/v4/jobs/request", host: "gitlab.mydomain"
2021/07/15 15:12:54 [warn] 574#574: *202525 upstream server temporarily disabled while connecting to upstream, client: X.X.X.X, server: gitlab.berlioz.me, request: "POST /api/v4/jobs/request HTTP/1.1", upstream: "http://[::1]:XXX/api/v4/jobs/request", host: "gitlab.mydomain"
```

**Comment by fl0ppy-d1sk** [comment]
Hey @thelittlefireman,

Very strange one because `::1` is the IPv6 loopback... I assume that you use reverse proxy mode ? What kind of data you have in `REVERSE_PROXY_HOST_*` : IP, existing domains, docker service name, ... ?

**Comment by thelittlefireman** [comment]
That right i use reverse proxy mode and all of my multiple site are defined like this: 
' - gitlab.mydomain_REVERSE_PROXY_HOST=http://localhost:XXXX'

**Comment by thelittlefireman** [comment]
Maybe this could help:

[https://serverfault.com/questions/527317/disable-ipv6-in-nginx-proxy-pass](https://serverfault.com/questions/527317/disable-ipv6-in-nginx-proxy-pass)

and add something like this ?
```
location / {
    resolver 1.1.1.1 ipv6=off;
    proxy_pass https://example.com;
}
```

**Comment by fl0ppy-d1sk** [comment]
This is strange because the resolver directive with the ipv6=off flag is already defined at http context (see [here](https://github.com/bunkerity/bunkerized-nginx/blob/master/confs/global/nginx.conf#L75)).

Since you are using `http://localhost:XXXX`, can you confirm that you're using the host networking mode ?

**Comment by thelittlefireman** [comment]
arf you're right for the resolver.
My reverse proxy config doesn't change  from the first version of bunkerized-nginx ^^.  Yes I'm using the host networking mode for this container.

**Comment by fl0ppy-d1sk** [comment]
Until we find a solution maybe you can set `http://127.0.0.1:XXXX` to force IPv4 as a workaround ?

**Comment by thelittlefireman** [comment]
Thanks :) @fl0ppy-d1sk Change all localhost to 127.0.0.1 seems to work... strange bug BTW ^-^

**Comment by benchonaut** [comment]
basically the "upstream" directive would be the right place like

upstream mybackend { 
	server 172.18.0.5:8080 max_fails=0 fail_timeout=0;

}

since nginx' default behaviour will drop your upstream for a few sconds when your backend throws e.g. 502

**Comment by fl0ppy-d1sk** [comment]
Closing this as we will support upstreams in 1.6

**Comment by LeVraiRoiDHyrule** [comment]
Hi, I am having the same problem. I having lots and lots of those errors, on Jellyfin that I reverse proxy with BW. Example of an error I have:
```
2024/12/22 22:38:08 [error] 43164#43164: *46443 connect() failed (111: Connection refused) while connecting to upstream, client: 2a02:aa13:8241:1300:40c7:cab8:d0e1:4eed, server: stream.REDACTED.com, request: "GET /Users/f2b5223f3eea4ef49cb063a8ee6f4bc4/Items?IncludeItemTypes=Movie&CollapseBoxSetItems=True&GroupItemsIntoCollections=True&Recursive=True&IsMissing=False&Fields=DateCreated,EpisodeCount,SeasonCount,Path,Genres,Studios,Etag,Taglines,SortName,RecursiveItemCount,ChildCount,ProductionLocations,CriticRating,OfficialRating,CommunityRating,PremiereDate,ProductionYear,AirTime,Status,Tags,MediaStreams,Overview&ImageTypeLimit=1&ParentId=db4c1708cbb5dd1676284a40f2950aba&format=json&Filters=IsResumable&SortBy=DatePlayed&SortOrder=Descending&Limit=20 HTTP/1.1", upstream: "http://[2001:db8::6]:8096/Users/f2b5223f3eea4ef49cb063a8ee6f4bc4/Items?IncludeItemTypes=Movie&CollapseBoxSetItems=True&GroupItemsIntoCollections=True&Recursive=True&IsMissing=False&Fields=DateCreated,EpisodeCount,SeasonCount,Path,Genres,Studios,Etag,Taglines,SortName,RecursiveItemCount,ChildCount,ProductionLocations,CriticRating,OfficialRating,CommunityRating,PremiereDate,ProductionYear,AirTime,Status,Tags,MediaStreams,Overview&ImageTypeLimit=1&ParentId=db4c1708cbb5dd1676284a40f2950aba&format=json&Filters=IsResumable&SortBy=DatePlayed&SortOrder=Descending&Limit=20", host: "stream.REDACTED.com"
```

Jellyfin is completely unusable when reverse proxied with BW (whereas it works perfectly with Caddy). Playback stops after a few seconds, on all clients. It doesn't come from the clients and doesn't come from Jellyfin itself which only sees that the playback got stopped. So I am 90% it is because of BW but I have no idea what setting is involved. I don't know if it is because of these errors.

Jellyfin is currently proxied with the following settings:
```
    labels:
      - "bunkerweb.SERVER_NAME=stream.${DOMAIN}"
      - "bunkerweb.USE_REVERSE_PROXY=yes"
      - "bunkerweb.REVERSE_PROXY_URL=/"
      - "bunkerweb.REVERSE_PROXY_HOST=http://jellyfin:8096"
      - "bunkerweb.REVERSE_PROXY_WS=yes"
      - "bunkerweb.ALLOWED_METHODS=GET|POST|HEAD|PUT|DELETE|PATCH"
      - "bunkerweb.REVERSE_PROXY_BUFFERING=no"
      - "bunkerweb.USE_BAD_BEHAVIOR=no"
      - "bunkerweb.REVERSE_PROXY_KEEPALIVE=yes"
      - "bunkerweb.USE_LIMIT_CONN=no"
      - "bunkerweb.USE_LIMIT_REQ=no"
      - "bunkerweb.LIMIT_REQ_RATE=${LIMITNORMAL}r/s"
      - |
        bunkerweb.CUSTOM_CONF_MODSEC_jellyfin=
        SecRuleRemoveById 941160
```

Could you tell me more about upstreams in 1.6 @fl0ppy-d1sk ? I am on 1.6-beta and searched in the doc but I don't see what it refers to.
Thanks in advance for any answer.
