### ISSUE TITLE
[BUG] Issue with PATCH Method Handling in BunkerWeb for Cloudflare WordPress Plugin

### ISSUE THREAD

**Issue by psychedelicu** [bunkerity/bunkerweb#1618]
### What happened?

I'm trying to install and configure the Cloudflare WordPress plugin on my website (https://test.peacefulexperiences.com/wp-admin/admin-ajax.php?action=cloudflare_proxy) and I'm encountering issues with PATCH requests. Despite adding PATCH, GET, and POST methods in both the CORS and Reverse Proxy Cache Methods sections of the BunkerWeb web GUI, I consistently receive a 405 Method Not Allowed error when sending PATCH requests.

### How to reproduce?

Steps to Reproduce:

Install the Cloudflare WordPress plugin.
Attempt to send a PATCH request to admin-ajax.php?action=cloudflare_proxy.
Configure the following in BunkerWeb:
Added PATCH, GET, POST to CORS.
Added PATCH, GET, POST to Reverse Proxy Cache Methods.
Despite this configuration, the PATCH method is still blocked with a 405 error.

### BunkerWeb version

1.5.10

### What integration are you using?

Docker

### Removed private data

- [X] I have removed all private data from the configuration file and the logs

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TheophileDiot** [comment]
Hi @psychedelicu, thank you for opening this issue!
Is this related to the issue I saw on Discord where the problem was due to a misconfiguration in the `ALLOWED_METHODS` setting ?

**Comment by psychedelicu** [comment]
Yes, I didn't see that there is a 3rd option where you can set this as well.

For other people like me who don't pay attention, you need to add PATCH to Misc->Allowed methods. 

Thanks!
