### ISSUE TITLE
[BUG] when i write ROOT_FOLDER, to end of my path adding domain name

### ISSUE THREAD

**Issue by derdek** [bunkerity/bunkerweb#166]
**How to reproduce**
I write example.com_ROOT_FOLDER = /www/example.com/public
In config files i see /www/example.com/public/example.com

**Comment by fl0ppy-d1sk** [comment]
Hello @derdek,

That's not a bug, but a feature ! This is the intended behavior when using both `ROOT_FOLDER` and `MULTISITE=yes`.
Maybe the `ROOT_SITE_SUBFOLDER` environment variable can help you ? You have an example [here](https://github.com/bunkerity/bunkerized-nginx/tree/master/examples/multisite-custom-subfolders).

If that doesn't help, can you explain your use case with details and what feature you would like to have (e.g. : a new env var ?) ?
