### ISSUE TITLE
[BUG] Reverse Proxy Headers UI - Invalid value

### ISSUE THREAD

**Issue by tgregory86** [bunkerity/bunkerweb#1701]
### What happened?

When configuring reverse proxy headers on a services in the UI, the UI reports that that values are invalid and will not allow you to save the config. 

### How to reproduce?

Configure reverse proxy headers in the UI as directed in the Docs. I have tried different combinations of values and they all report "invalid value"
![image](https://github.com/user-attachments/assets/af0ccd96-f895-48fc-bf6b-05c47e20dd78)
![image](https://github.com/user-attachments/assets/44adb6fe-1ea4-4865-8339-a5608c2e8504)
![image](https://github.com/user-attachments/assets/72342e8a-1852-4e0d-aa4c-7e4fd409d592)

### Configuration file(s) (yaml or .env)

```YAML
n/a
```

### Relevant log output

```shell
n/a
```

### BunkerWeb version

1.5.11

### What integration are you using?

Docker

### Linux distribution (if applicable)

Ubuntu Server 24.04

### Removed private data

- [X] I have removed all private data from the configuration file and the logs

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TheophileDiot** [comment]
Hi @tgregory86, thank you for opening this issue.
Here's the regex for the setting with working examples: https://regex101.com/r/L8xGSj/1

**Comment by tgregory86** [comment]
I understand now, you need to leave off the last semicolon, since its automatically appended to the config.

**Comment by jujugoboom** [comment]
I just stumbled across this and after looking at the regex, I'm not sure it handles input as expected. The lookaround `(?!.*\2 )` causes some headers to need specific ordering to be able to set (you can't do `Host $host; X-Forwarded-Host $host` but you can do `X-Forwarded-Host $host; Host $host`)
