### ISSUE TITLE
[FEATURE] cloudflare support

### ISSUE THREAD

**Issue by rafalohaki** [bunkerity/bunkerweb#174]
add cloudflare support to paste crt from cloudflare instead of letsecrypt

**Comment by fl0ppy-d1sk** [comment]
Hello @rafalohaki,

Are you referring to certificates [signed by Cloudflare Origin CA](https://developers.cloudflare.com/ssl/origin-configuration/origin-ca) ?

**Comment by rafalohaki** [comment]
yes

**Comment by fl0ppy-d1sk** [comment]
Here is a blog post about CF support with BW : https://www.bunkerweb.io/blog/post/bunkerweb-with-cloudflare

We also plan to create a dedicated CF plugin for BW 1.6.0
