### ISSUE TITLE
[FEATURE] Auto configure modsecurity with ALLOWED_METHODS arguments

### ISSUE THREAD

**Issue by thelittlefireman** [bunkerity/bunkerweb#175]
**What's needed and why ?**
Could it be possible to automatically add a rule to modsecurity for site that's edit the ALLOWED_METHODS variable ?
Something like this would be perfect :+1: 

if ALLOWED_METHODS is set then add:
```
SecAction \
--
"id:900200,\
phase:1,\
nolog,\
pass,\
t:none,\
setvar:'tx.allowed_methods=${ALLOWED_METHODS}'"


``` 

to the config
fi

**Implementations ideas (optional)**
How it should be used and integrated into the project ? List some posts, research papers or codes that we can use as implementation.

**Comment by fl0ppy-d1sk** [comment]
Hey @thelittlefireman,

Nice suggestion in my opinion but we should turn it off with something like `AUTOMATIC_MODSECURITY_CONFIG` just in case.

**Comment by fl0ppy-d1sk** [comment]
Hello @thelittlefireman,

Done in the new 1.4.0 version, thank you for the idea.
