### ISSUE TITLE
[DOC] How to use the parameter: Reverse proxy includes

### ISSUE THREAD

**Issue by rdrouche** [bunkerity/bunkerweb#1768]
### Description

Hi everyone,

I'm discovering the product which really seems to be great and I'm doing tests to replace our reverse proxy on Nginx.

In the reverse proxy configuration, I saw that there was the following parameter: Reverse proxy includes which normally allows to include parameters in the location part of the configuration.

Do you know how to use it? because normally this file should be placed in the /etc/nginx folder but I can't find anywhere how to do it.

I tried using the volume configuration in my docker-compose.yml file to map the file in Nginx, this prevents the container from starting.

If you can help me I thank you in advance.

Romain ;)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TheophileDiot** [comment]
Hi @rdrouche, there is a `REVERSE_PROXY_INCLUDES` setting that might help you with this: https://docs.bunkerweb.io/latest/settings/#reverse-proxy

**Comment by MaizalNme** [comment]
Dunno if it is a good solution, but it solved my problem.

You can create the file to include in /usr/share/bunkerweb/confs **without extension** and use it in the reverse_proxy_includes parameter.

Bunkerweb will copy the file to /etc/nginx once you do any modification to a service.

**Comment by rdrouche** [comment]
> Dunno if it is a good solution, but it solved my problem.
> 
> You can create the file to include in /usr/share/bunkerweb/confs **without extension** and use it in the reverse_proxy_includes parameter.
> 
> Bunkerweb will copy the file to /etc/nginx once you do any modification to a service.

Hi,

Thanks for your feedback, I will try this :)
