### ISSUE TITLE
[BUG] Reporting / Test SMTP fails due to SSL/TLS version number

### ISSUE THREAD

**Issue by ffpedraza** [bunkerity/bunkerweb#1781]
### What happened?

Error in UI: 

(Action error) Error while sending SMTP : Traceback (most recent call last): File "", line 120, in reporting File "/usr/lib/python3.12/smtplib.py", line 1022, in __init__ SMTP.__init__(self, host, port, local_hostname, timeout, File "/usr/lib/python3.12/smtplib.py", line 255, in __init__ (code, msg) = self.connect(host, port) ^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/lib/python3.12/smtplib.py", line 341, in connect self.sock = self._get_socket(host, port, self.timeout) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/lib/python3.12/smtplib.py", line 1029, in _get_socket new_socket = self.context.wrap_socket(new_socket, ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/lib/python3.12/ssl.py", line 455, in wrap_socket return self.sslsocket_class._create( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/lib/python3.12/ssl.py", line 1042, in _create self.do_handshake() File "/usr/lib/python3.12/ssl.py", line 1320, in do_handshake self._sslobj.do_handshake() ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1000) 

### How to reproduce?

Try to test SMTP for reporting, using the appropriate lines in configuration file (private data removed)
I am trying to send via office 365 server for HVE. It needs TLS. 

I have been able to send e-mail through the office 365 server with a simple python script running in the same machine where I have Bunkerweb, and it didn't need any special SSL/TLS configuration. 
Code:
...
context = ssl.create_default_context()
...
server = smtplib.SMTP(smtp_server,port)
server.ehlo() 
server.starttls(context=context) 
server.ehlo() 
server.login(from_addr, password)
server.sendmail( from_addr, to_addr, message)
...

### Configuration file(s) (yaml or .env)

```YAML
REPORTING_SCHEDULE=daily
REPORTING_SMTP_EMAILS= ****
REPORTING_SMTP_HOST=***.office365.com
REPORTING_SMTP_PORT=587
REPORTING_SMTP_FROM_EMAIL= ****
REPORTING_SMTP_SSL=yes
REPORTING_SMTP_FROM_USER= ****
REPORTING_SMTP_FROM_PASSWORD= ****
REPORTING_SMTP_SUBJECT=Bunkerweb-Reports
```

### Relevant log output

```shell
024-12-05 23:27:45,568 [JOBS.SEND-REPORTING] [2585] [ℹ️ ] - Connecting to SMTP s
erver ****.office365.com on port 587 ...
2024-12-05 23:27:45,590 [JOBS.SEND-REPORTING] [2585] [❌] - Error while configur
ing SMTP: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1000)
2024-12-05 23:27:45,598 [JOBS.SEND-REPORTING] [2585] [❌] - All webhooks and ema
ils failed, will try to send report again next time ...
2024-12-05 23:27:45,714 [SCHEDULER] [1480] [❌] - Error while executing job send
-reporting from plugin reporting
```

### BunkerWeb version

1.5.12

### What integration are you using?

Linux

### Linux distribution (if applicable)

Ubuntu 24.04 LTS

### Removed private data

- [X] I have removed all private data from the configuration file and the logs

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ffpedraza** [comment]
Hi @fl0ppy-d1sk , I changed to REPORTING_SMTP_SSL=TLS and the SMTP test is working perfect now. It does not work with SSL, but probably shouldn't, so everything OK. Thank you!!!

**Comment by TheophileDiot** [comment]
Hi @ffpedraza, I think the issue is now resolved. Therefor I'm gonna close that one :smile:
