### ISSUE TITLE
[FEATURE] Make challenge pages editable

### ISSUE THREAD

**Issue by Myzel394** [bunkerity/bunkerweb#183]
**What's needed and why ?**
Since error pages can already be edited, it would be cool if the challenge pages could also have this functionality (and I personally don't like this extreme blueish-tone :D).

**Implementations ideas (optional)**
Add a new environment variable (maybe `PAGES`; I would use plural since `ERRORS` is also plural) and use the same format as `ERRORS`. Something like:
```
- PAGES=CHALLENGE_JAVASCRIPT=myfile.html CHALLENGE_CAPTCHA=myotherfile.html
```

**EDIT**
By "challenge pages" I mean the pages that occur when using `USE_ANTIBOT=javascript|captcha|recaptcha`.

**Comment by Myzel394** [comment]
I don't understand exactly what you mean. I would like to create custom pages and use them instead of the default ones.

**Comment by msalmanfarisi** [comment]
I meant i tested ANTIBOT by adding recaptcha v3 but it didn't work at all. maybe you could share your experience on this?

**Comment by Myzel394** [comment]
Oh okay. I haven't tested reCaptcha yet. I think you should open a bug issue for that

**Comment by fl0ppy-d1sk** [comment]
Hello @Myzel394,

Another alternative would be to edit the [templates](https://github.com/bunkerity/bunkerized-nginx/tree/master/antibot) and build the image by hand. What do you think ?

**Comment by Myzel394** [comment]
I think having an environmental variables is much easier than manually rebuilding the image.
