### ISSUE TITLE
[BUG] Set - REVERSE_PROXY_AUTH_REQUEST_SET_999 failed in WebUI

### ISSUE THREAD

**Issue by Ghosty01** [bunkerity/bunkerweb#1836]
### What happened?

When try to set - REVERSE_PROXY_AUTH_REQUEST_SET_x=$$auth_cookie $$upstream_http_set_cookie in the Web UI i cant save the config -> 

![image](https://github.com/user-attachments/assets/0e7c4b73-b417-43c0-98ec-668c93ca5fed)

### How to reproduce?

Version: 1.5.12

Try to set the Field in the WebUI under ReverseProxy: 

"Reverse proxy auth request set #1" to  ->  $$auth_cookie $$upstream_http_set_cookie

### BunkerWeb version

1.5.12

### What integration are you using?

Docker

### Linux distribution (if applicable)

docker

### Removed private data

- [X] I have removed all private data from the configuration file and the logs

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TheophileDiot** [comment]
Hi @Ghosty01, the double `$` signs are only needed when setting the variables in a docker-compose file as it will interpret them as variables with only one `$` sign.
https://regex101.com/r/GNYmYY/1
