### ISSUE TITLE
[BUG]/[Feature] Wordpress 'pretty' permalinks - 404 error

### ISSUE THREAD

**Issue by Peelige** [bunkerity/bunkerweb#193]
**Description**
Hi, first of thanks for the fantastic software, keep up the excellent work.  I have bunkerized-nginx deployed in multisite config, along with the bunkerized-nginx-ui.  

One of the hosts is set to serve files and utilise remote php, hosting a wordpress site.  The bug here is that any of the pretty permalinks within the site e.g domain.com/about-us or domain.com/shop/ returns a 404 error. 

This can be overcome by manually commenting out the self generated code within serve-files.conf within the nginx config and replacing as follows:

root /opt/bunkerized-nginx/www/www.domain.com;
index index.html index.php;
#try_files $uri $uri/ =404;
**try_files $uri $uri/ /index.php?q=$uri&$args;** 

The manual edits do not persist and are overwritten next time anything is saved within the ui.

more on the issue here: [https://www.digitalocean.com/community/questions/custom-wordpress-404-page-not-loading-nginx-404-page-loading-instead](url)

**How to reproduce**
deploy a wordpress instance within a host within multisite bunkerized-nginx

**SUGGESTION**
My suggestion would be to add a toggle switch within the UI something like 'serve permalinks', and then update the serve-files.conf as necessary ?

Thanks in advance.

**Comment by Peelige** [comment]
If it's at all relevant, the remote php instance is crunchgeek/php-fpm

**Comment by fl0ppy-d1sk** [comment]
Hello @Peelige,

What about using [custom configuration](https://bunkerized-nginx.readthedocs.io/en/latest/special_folders.html#server-configurations) instead ? You have a WordPress example with permalinks [here](https://github.com/bunkerity/bunkerized-nginx/tree/master/examples/wordpress).
