### ISSUE TITLE
[QUESTION] Does bunkerized-nginx support DNS-01 challenge for Let's Encrypt?

### ISSUE THREAD

**Issue by axeleroy** [bunkerity/bunkerweb#201]
Hello,

I was wondering if bunkerized-nginx's Let's Encrypt implementation supports ACME's [DNS-01 challenge](https://letsencrypt.org/docs/challenge-types/#dns-01-challenge).

I'm looking into having bunkerized-nginx as a reverse proxy with HTTPS for services that should only be accessible from within my network (with a DNS entry like `CNAME *.private.publicdomain.tld => 192.168.0.XXX`).

Is it currently supported?
Thanks

**Comment by fl0ppy-d1sk** [comment]
Example has been removed in 1.4.0, we need to get it back again.

**Comment by fl0ppy-d1sk** [comment]
Various certbot DNS (automated) examples have been added to the [examples directory](https://github.com/bunkerity/bunkerweb/tree/master/examples).
