### ISSUE TITLE
[FEATURE] Add option for timeout

### ISSUE THREAD

**Issue by Myzel394** [bunkerity/bunkerweb#202]
**What's needed and why ?**
It would be nice if we could change the timeout (both for client and upstream). This is especially helpful when dealing with errors such as `*3743 client prematurely closed connection while processing HTTP/2 connection` :C (context: I'm trying to get a [funkwhale](https://funkwhale.audio) working and songs are sometimes aborted when the processing takes longer than the default timeout).

**Implementations ideas (optional)**
Add a environmental variable named something like `CLIENT_TIMEOUT` or so :D

**Comment by jdqw210** [comment]
Any way I could get this bumped up?

**Comment by Myzel394** [comment]
@jdqw210 If you are also trying to setup funkwhale, just restart your containers, after a few tries it randomly started to work ¯\_(ツ)_/¯. What also helps is to buy better internet (worked for me at least)

**Comment by jdqw210** [comment]
No I'm just having timeouts on webpages containing a lot of .png files, for example. I wish I could buy better internet, I'm out in the middle of nowhere.

**Comment by fl0ppy-d1sk** [comment]
Hello @Myzel394 and @rmrf-sl4sh,

Proxy timeouts are now supported starting with 1.4.1 version. More info [here](https://docs.bunkerweb.io/1.4/settings/#reverse-proxy).
