### ISSUE TITLE
[BUG] Can't write to the templates directory : /etc/nginx

### ISSUE THREAD

**Issue by Visalyaputra** [bunkerity/bunkerweb#204]
**Description**
Concise description of what you're trying to do, the expected behavior and the current bug.
I do not know if this is a bug or not. i just install it on my linux server and follow the procedure for linux integration then after i execute bunkerized-nginx a error appear

**Logs**
The logs generated by bunkerized-nginx. **DON'T FORGET TO REMOVE PRIVATE DATA LIKE IP ADDRESSES !**

$ bunkerized-nginx
[*] Generate configuration files
[!] Error from command : /opt/bunkerized-nginx/gen/main.py --settings /opt/bunkerized-nginx/settings.json --templates /opt/bunkerized-nginx/confs --output /etc/nginx --variables /opt/bunkerized-nginx/variables.env
[!] Can't write to the templates directory : /etc/nginx

**Comment by hjorslev** [comment]
I get the same error. I just installed bunkerized-nginx today using this guide: https://bunkerized-nginx.readthedocs.io/en/latest/integrations.html#linux

**Comment by kppetro** [comment]
Replace ${port} with a port number - worked for me. It probably is a hacked off solution but all I have sorry

  sudo chown -R nginx:nginx /etc/nginx
    sudo sed -i 's/%HTTP_PORT%/${port}/' /opt/bunkerized-nginx/confs/global/nginx-temp.conf
    sudo sed -i 's/%USE_API%//' /opt/bunkerized-nginx/confs/global/nginx-temp.conf
    sudo bunkerized-nginx

**Comment by fl0ppy-d1sk** [comment]
Hello @Visalyaputra and @hjorslev,

It should be fixed in the new 1.4.0 version. Feel free to test it and open a new issue if needed.
