### ISSUE TITLE
**Rootless** docker or podman machine id issue on RPi4 (arm64) [BUG]

### ISSUE THREAD

**Issue by sensharma** [bunkerity/bunkerweb#208]
**Description**
Hi, 
Following the [docker integration docs](https://bunkerized-nginx.readthedocs.io/en/latest/integrations.html#docker) I am trying to run with **rootless** docker/podman on Ubuntu server on RPi4 (arm64). I get the error in the logs below for both rootless docker and podman.

Please note:

1. [Here](https://github.com/bunkerity/bunkerized-nginx/issues/105#issuecomment-803613488) it is mentioned that this runs as UID/GID 101. But I seem to already have user and group using ID 101:
`
systemd-timesync:x:100:101:systemd Time Synchronization,,,:/run/systemd:/usr/sbin/nologin
systemd-network:x:101:103:systemd Network Management,,,:/run/systemd:/usr/sbin/nologin
`
2. I have tried the following permissions for local `www` and `certs` dirs:
- `chown root:101 www certs`
- `chown abc:101 www certs`
- `chown abc:abc www certs`

where _abc_ is the user running rootless docker or podman. The rights are set as 750 for `www` and 770 for `certs` as in the linked docs.

3. Removing the `certs` volume map produces the same error for the `www` volume. Removing both seems to to run the container fine as I can reach it over http (resulting in the expected 403 error).

**How to reproduce**

`
docker run -d --rm -p 80:8080 -p 443:8443 -v "${PWD}/www:/www:ro" -v "${PWD}/certs:/etc/letsencrypt" --name bnginx bunkerity/bunkerized-nginx
`
Just trying to run without a domain or automatic letsencrypt for now

**Logs**
[2021-11-10 17:41:40] entrypoint - INFO - starting bunkerized-nginx ...
[2021-11-10 17:41:40] entrypoint - INFO - configuring bunkerized-nginx ...
[!] ERROR - wrong permissions on /etc/letsencrypt

Is there an issue with running this container with rootless docker/podman or are there any further settings that need to be configured?

**Comment by sensharma** [comment]
Update: After a lot of experimentation, it turns out that the problem was not really a bug, but how the UID mapping works in rootless mode, including a slight difference in docker and podman rootless mode, with consequences for the chown commands for the files/dirs. So that was not a bug, just something not yet in the documentation.

However, now that I understand how to do the UID mappings, I get the following error from the logs when I tri it on RPi4 (arm64) when I map a local dir:

`nginx: [error] [REMOTE API] USE_REMOTE_API is set to yes but machine ID is not generated - communication with https://api.bunkerity.com/bunkerized won't work`

I have checked that the machine-id is properly configured at `/etc/machine-id`

Importantly, this does not happen if 

1. I just use a volume instead of a dir map, when it somehow seems to find the machine-id (but I much prefer working with local dirs).
2. On an intel machine, where I now seem to be able to run this in rootless mode without a problem.

**Comment by fl0ppy-d1sk** [comment]
Hello @sensharma,

Thanks for sharing your experimentation. I think that we need to document the docker and podman rootless case.

**Comment by alexanderadam** [comment]
> Update: After a lot of experimentation, it turns out that the problem was not really a bug, but how the UID mapping works in rootless mode, including a slight difference in docker and podman rootless mode, with consequences for the chown commands for the files/dirs. So that was not a bug, just something not yet in the documentation.

Would you please mind to share how you end up setting up Bunkerweb in rootless Podman?

**Comment by fl0ppy-d1sk** [comment]
Hello @sensharma and @alexanderadam,

We now have some tips about rootless Docker and podman. More info here : https://docs.bunkerweb.io/1.4/integrations/

**Comment by sensharma** [comment]
> 

Thank you. I'm going to experiment with this in a few weeks. Will get back to you in case of any issues.

**Comment by sensharma** [comment]
> Hello @sensharma and @alexanderadam,
> 
> We now have some tips about rootless Docker and podman. More info here : https://docs.bunkerweb.io/1.4/integrations/

Thank you. I'm going to experiment with this in a few weeks. Will get back to you in case of any issues.
