### ISSUE TITLE
[BUG] "No instances to show ..." in web UI

### ISSUE THREAD

**Issue by boozedog** [bunkerity/bunkerweb#212]
**Description**
I've got web UI up and running and I can view/edit server config under Services. However, when I click Instances, I get "No instances to show ..."

**How to reproduce**
I'm using Docker on local dev environment and for simplicity/testing I'm connecting the UI container to Docker socket using `-v /var/run/docker.sock:/var/run/docker.sock:ro`

**Logs**
Not seeing anything relevant in any log

**Comment by fl0ppy-d1sk** [comment]
Hello @boozedog,

I would suggest you to try again with the last 1.4.0 version. If problem still persists, please open a new issue.
