### ISSUE TITLE
[BUG] Struggling with REVERSE_PROXY_URL and REVERSE_PROXY_HOST

### ISSUE THREAD

**Issue by boozedog** [bunkerity/bunkerweb#213]
**Description**
I'm struggling to get reverse proxy to work the way I want. I'm using Docker to run bunkerized-nginx .

I've got a url like this: `https://mybunkerized/api/dostuff?now`
I want it to proxy to another docker container like `http://containername:8080/dostuff?now`

I've tried a bunch of different combinations with slashes at the end and without and nothing seems to work.

**How to reproduce**
I tried with no trailing slashes on the HOST:
```
    --env REVERSE_PROXY_URL_1=/api \
    --env REVERSE_PROXY_HOST_1=http://containername:8080 \
```
The proxied host URL ends up being `http://containername:8080/api/dostuff?now`. This results in the proxy endpoint giving a 404 since it includes /api (which I don't want). The result is same even if I add / after REVERSE_PROXY_URL_1 like `/api/`.

If I add a slash to end of REVERSE_PROXY_HOST_1 then everything after the input URL gets ignored, and the proxy endpoint always ends up being `http://containername:8080/` with everything else dropped.

Am I missing something obvious here!?

**Logs**
The bunkerized-nginx logs show 404 as my proxied service is returning 404.

**Comment by HugooB** [comment]
Maybe you are forgetting `REVERSE_PROXY=yes`?

This is my working configuration in docker-compose.yml:

```
      - USE_REVERSE_PROXY=yes
      - REVERSE_PROXY_URL=/api/v1/
      - REVERSE_PROXY_HOST=http://api:5000
```

**Comment by boozedog** [comment]
Thanks @HugooB `USE_REVERSE_PROXY=yes` is there and the proxy is functioning. But it's not working the way I want.

> I've got a url like this: https://mybunkerized/api/dostuff?now
> I want it to proxy to another docker container like http://containername:8080/dostuff?now

What such a config look like? I've tried various combinations of slashes and no slashes to no avail. See OP for more details.

**Comment by DeadPackets** [comment]
Strugglign with this issue as well.

**Comment by mx5gr** [comment]
Hi,

under the latest version 1.3.2, it does not work for me as well!

Configuration:

`
docker run -d \
--name bunkerized-nginx \
--network bunkerized-ui-net \
-p 80:8080 \
-p 8443:8443 \
-v "/opt/bunkerized/certs:/etc/letsencrypt" \
-v "bunkerized-vol:/etc/nginx" \
-v "/opt/bunkerized/www:/www:ro" \
-v "/opt/bunkerized/server-confs:/server-confs:ro" \
-v "/opt/bunkerized/log:/var/log" \
--restart unless-stopped \
-e SERVER_NAME=server.test.com \
-e MULTISITE=no \
-e USE_API=yes \
-e API_URI=/dfdsafasaas \
-e USE_PROXY_CACHE=yes \
-e USE_CLIENT_CACHE=yes \
-e USE_GZIP=yes \
-e AUTO_LETS_ENCRYPT=yes \
-e REDIRECT_HTTP_TO_HTTPS=yes \
-e "HTTPS_PROTOCOLS=TLSv1.2 TLSv1.3" \
-e HTTP2=yes \
-e server.test.com_USE_REVERSE_PROXY=yes \
-e server.test.com_REVERSE_PROXY_URL_1=/admin/ \
-e server.test.com_REVERSE_PROXY_HOST_1=http://bunkerized-ui:5000 \
-e "server.test.com_REVERSE_PROXY_HEADERS_1=X-Script-Name /admin" \
-e server.test.com_REVERSE_PROXY_URL_2=/api2/ \
-e server.test.com_REVERSE_PROXY_HOST_2=http://api2 \
-e "server.test.com_REVERSE_PROXY_HEADERS_2=X-Script-Name /api2" \
-e server.test.com_REVERSE_PROXY_URL_3=/api3/ \
-e server.test.com_REVERSE_PROXY_HOST_3=http://api3 \
-e "server.test.com_REVERSE_PROXY_HEADERS_3=X-Script-Name /api3" \
-e server.test.com_USE_MODSECURITY=no \
-l bunkerized-nginx.UI \
bunkerity/bunkerized-nginx
`

**Comment by fl0ppy-d1sk** [comment]
Hello @boozedog, @DeadPackets and @mx5gr,

I would suggest you to try again with the last 1.4.0 version. If problem still persists, please open a new issue.
