### ISSUE TITLE
[BUG] Looks like USE_PROXY_CACHE does not work.

### ISSUE THREAD

**Issue by makorne** [bunkerity/bunkerweb#214]
- MULTISITE=yes
      - USE_CLIENT_CACHE=yes
      - USE_PROXY_CACHE=yes
      - PROXY_CACHE_PATH_ZONE_SIZE=10m
      - PROXY_CACHE_PATH_PARAMS=max_size=100m
      - PROXY_CACHE_METHODS=GET HEAD
      - PROXY_CACHE_MIN_USES=2
      - PROXY_CACHE_VALID=200=10m 301=10m 302=1h 
     
No errors, MULTISITE app works  but no difference with USE_PROXY_CACHE being set or not.
All the same GET requests go to app.

**Comment by boozedog** [comment]
I'm having trouble getting PROXY_CACHE to work as well.

**Comment by fl0ppy-d1sk** [comment]
Hello @makorne and @boozedog,

It should be fixed now, I would suggest you to try the new 1.4.0 version and reopen a new issue if needed.
