### ISSUE TITLE
Has Fail2Ban been removed?

### ISSUE THREAD

**Issue by DeadPackets** [bunkerity/bunkerweb#217]
I was trying to get banned by running attacks on the server, and I do get banned. However it is not an IP ban like fail2ban, but instead is simply just a ban where I get 403 responses. I think its better to have an actual firewall block such as fail2ban.

**Comment by fl0ppy-d1sk** [comment]
Hello @DeadPackets,

Yes fail2ban has been removed. I think a pragmatic solution would be to use the specific 444 code from NGINX. Users will have the choice between using 403 (forbidden page) codes or 444 (connection close).

**Comment by baradhili** [comment]
You can tie fail2ban to 403 errors.. https://codepre.com/configuring-fail2ban-to-ban-403-forbidden-requests-in-nginx.html

**Comment by fl0ppy-d1sk** [comment]
Hello @DeadPackets and @baradhili,

We now support choosing between 403 (standard HTTP forbidden) or 444 (close connection) more info here : https://docs.bunkerweb.io/1.4/security-tuning/#deny-status-code
