### ISSUE TITLE
[BUG] ClamAV Plugin is not loaded

### ISSUE THREAD

**Issue by mwester117** [bunkerity/bunkerweb#222]
Hello,

I tried to install the clamav plugin. I followed the instructions described [here](https://bunkerized-nginx.readthedocs.io/en/latest/plugins.html?highlight=plugin#use-a-plugin).
The cloned[ git repository](https://github.com/bunkerity/bunkerized-nginx-clamav) is mounted correctly to /plugins/clamav inside the container.
The plugin.json is correctly configured and I can curl the ClamAV API container URL. 
I expected some log message like this (copied from [documentation](https://bunkerized-nginx.readthedocs.io/en/latest/plugins.html?highlight=plugin#use-a-plugin)):
`2021/06/05 09:19:47 [error] 104#104: [PLUGINS] *NOT AN ERROR* plugin MyPlugin/1.0 has been loaded`
But no log entry appears.

I uploaded an eicar test virus via PUT request and it was not detected. Therefore the plugin is not working or I'm missing something.

I found a related issue in the bunkerized-nginx-clamav repository:
https://github.com/bunkerity/bunkerized-nginx-clamav/issues/2

A possible solution is provided by the author. Can you please have a look at it?

I'm using latest bunkerized-nginx alpine container. Do you need more information?

Thanks for your help!

**Comment by fl0ppy-d1sk** [comment]
Hello @mwester117,

A lot has changed and I suggest you to try it again with the new 1.4.0 version and new plugin from [here](https://github.com/bunkerity/bunkerweb-plugins/tree/main/clamav). Don't hesitate to open a new issue if needed.
