### ISSUE TITLE
Dockerfile should not export ports by default

### ISSUE THREAD

**Issue by ip6li** [bunkerity/bunkerweb#223]
Exposition of ports should be controlled by docker-compose.yaml or docker command. This would achieve more control on multihomed hosts. Line
`EXPOSE 8080/tcp 8443/tcp`
should be removed from Dockerfile.

**Comment by TheophileDiot** [comment]
Hi @ip6li according to the docker documentation, 

> The EXPOSE instruction does not actually publish the port. It functions as a type of documentation between the person who builds the image and the person who runs the container, about which ports are intended to be published. To actually publish the port when running the container, use the -p flag on docker run to publish and map one or more ports, or the -P flag to publish all exposed ports and map them to high-order ports.

*[source](https://docs.docker.com/engine/reference/builder/#expose)*

If you think about something else concerning the exposed port that I missed out i'll be happy to listen about it, thanks.

**Comment by fl0ppy-d1sk** [comment]
Closing this because it looks like it's not an issue.
