### ISSUE TITLE
[BUG] examples/prestashop/docker-compose.yml - cannot login into prestashop backend. [incl. solution]

### ISSUE THREAD

**Issue by jerryhopper** [bunkerity/bunkerweb#225]
**Description**
The default prestashop-example setup works, but doesnt allow you to login into the backend.

**How to reproduce**
Just setup the example, and try to login into the backend

**Logs**
No logs available.

**Solution**

The default prestashop installation requires SSL when logging into the backend, when using nginx as rev-proxy a the X-Forwarded-Proto needs to be set to https in order to 'fool' the backend and make it think its being requested via https.
  
The prestashop.conf needs a minor tweak to allow logging into the backend.
<pre>
proxy_set_header X-Forwarded-Proto https;
</pre>

The ./server-confs/prestashop.conf should look something like this:
<pre>
# [REQUIRED EDIT] Change this block to your admin folder
location /myadmin/ {
        # Fixes backend login error.
	proxy_set_header X-Forwarded-Proto https;
	if (!-e $request_filename) {
		rewrite ^/.*$ /myadmin/index.php last;
	}
}
</pre>

i Hope this helps someone.

**Comment by fl0ppy-d1sk** [comment]
Hello @jerryhopper, it should be fixed with the new example and last 1.4.0 version.
