### ISSUE TITLE
[BUG] gpg: Can't check signature: No public key

### ISSUE THREAD

**Issue by circa1741** [bunkerity/bunkerweb#226]
**Description**
"gpg: Can't check signature: No public key" message is received when using the Linux install script procedure.

**How to reproduce**
Follow the steps outlined in https://bunkerized-nginx.readthedocs.io/en/latest/integrations.html#linux. The message is received after executing the step:
gpg --verify /tmp/bunkerized-nginx.sh.asc /tmp/bunkerized-nginx.sh

**Logs**
root@NGINX:~# curl -fsSL https://github.com/bunkerity/bunkerized-nginx/releases/download/v1.3.2/linux-install.sh -o /tmp/bunkerized-nginx.sh

root@NGINX:~# curl -fsSL https://github.com/bunkerity/bunkerized-nginx/releases/download/v1.3.2/linux-install.sh.asc -o /tmp/bunkerized-nginx.sh.asc

root@NGINX:~# gpg --auto-key-locate hkps://keys.openpgp.org --locate-keys contact@bunkerity.com
gpg: directory '/root/.gnupg' created
gpg: keybox '/root/.gnupg/pubring.kbx' created
gpg: /root/.gnupg/trustdb.gpg: trustdb created
gpg: key 3D80806F12602A7C: public key "bunkerity-pgp <contact@bunkerity.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1
pub   rsa4096 2021-04-24 [SC] [expires: 2023-04-24]
      C3BF128E4715C570AAEE14AD3D80806F12602A7C
uid           [ unknown] bunkerity-pgp <contact@bunkerity.com>
sub   rsa4096 2021-04-24 [E] [expires: 2023-04-24]

root@NGINX:~# gpg --verify /tmp/bunkerized-nginx.sh.asc /tmp/bunkerized-nginx.sh
gpg: Signature made Sun Oct 24 16:30:21 2021 UTC
gpg:                using RSA key 215F43D2EA14C60120E084A35DC39CCA44171D5A
**gpg: Can't check signature: No public key**

**Comment by fl0ppy-d1sk** [comment]
Hello @circa1741, fixed in the last 1.4.0 version.
