### ISSUE TITLE
[BUG] Error from command : ... certbot-*.py ... No such file or directory

### ISSUE THREAD

**Issue by circa1741** [bunkerity/bunkerweb#227]
**Description**
"Error from command : chmod 750 /opt/bunkerized-nginx/jobs/certbot-*.py
chmod: cannot access '/opt/bunkerized-nginx/jobs/certbot-*.py': No such file or directory" message is received when using the Linux install script procedure.

**How to reproduce**
Follow the steps outlined in https://bunkerized-nginx.readthedocs.io/en/latest/integrations.html#linux. The message is received after executing the step:
/tmp/bunkerized-nginx.sh

**Logs**
root@NGINX:~# /tmp/bunkerized-nginx.sh
[*] Prepare /tmp/bunkerized-nginx
[*] Prepare /opt/bunkerized-nginx
[*] Add nginx official repository
[*] Install nginx
[*] Detected nginx version 1.20.2
/!\ Warning : we recommend you to use nginx v1.20.1, you should uninstall your nginx version and run this script again ! /!\
[*] Stop nginx service
[*] Update packet list
[*] Install compilation dependencies
[*] Download lua-5.1.5
[*] Compile and install lua-5.1.5
[*] Download maxmind/libmaxminddb
[*] Compile and install libmaxminddb
[*] Clone SpiderLabs/ModSecurity
[*] Compile and install ModSecurity
[*] Clone coreruleset/coreruleset
[*] Install coreruleset
[*] Clone SpiderLabs/ModSecurity-nginx
[*] Clone openresty/headers-more-nginx-module
[*] Clone leev/ngx_http_geoip2_module
[*] Clone AirisX/nginx_cookie_flag_module
[*] Clone google/ngx_brotli
[*] Clone openresty/luajit2
[*] Compile luajit2
[*] Install luajit2
[*] Clone openresty/lua-resty-core
[*] Install lua-resty-core
[*] Clone openresty/lua-resty-lrucache
[*] Install lua-resty-lrucache
[*] Clone openresty/lua-resty-dns
[*] Install lua-resty-dns
[*] Clone bungle/lua-resty-session
[*] Install lua-resty-session
[*] Clone bungle/lua-resty-random
[*] Install lua-resty-random
[*] Clone openresty/lua-resty-string
[*] Install lua-resty-string
[*] Clone openresty/lua-cjson
[*] Compile lua-cjson
[*] Install lua-cjson
[*] Clone ittner/lua-gd
[*] Compile lua-gd
[*] Install lua-gd
[*] Clone ledgetech/lua-resty-http
[*] Install lua-resty-http
[*] Clone Neopallium/lualogging
[*] Install lualogging
[*] Clone diegonehab/luasocket
[*] Compile luasocket
[*] Install luasocket
[*] Clone brunoos/luasec
[*] Compile luasec
[*] Install luasec
[*] Clone hamishforbes/lua-resty-iputils
[*] Install lua-resty-iputils
[*] Clone openresty/lua-resty-redis
[*] Install lua-resty-redis
[*] Clone openresty/lua-resty-upload
[*] Install lua-resty-upload
[*] Download nginx-1.20.2.tar.gz
[*] Compile dynamic modules
[*] Cleaning /tmp/bunkerized-nginx
[*] Dependencies for bunkerized-nginx successfully installed !
[*] Update packet list
[*] Install runtime dependencies
[*] Clone bunkerity/bunkerized-nginx
[*] Install python dependencies
[*] Copy generator
[*] Copy entrypoint
[*] Copy configs
[*] Copy jobs
[*] Copy LUA
[*] Copy antibot
[*] Copy defaults
[*] Copy settings
[*] Copy sample variables.env
[*] Copy UI
[*] Copy bunkerized-nginx
[*] Copy VERSION
[*] Create /opt/bunkerized-nginx/www folder
[*] Create /opt/bunkerized-nginx/http-confs folder
[*] Create /opt/bunkerized-nginx/server-confs folder
[*] Create /opt/bunkerized-nginx/modsec-confs folder
[*] Create /opt/bunkerized-nginx/modsec-crs-confs folder
[*] Create /opt/bunkerized-nginx/cache folder
[*] Create /opt/bunkerized-nginx/pre-server-confs folder
[*] Create /opt/bunkerized-nginx/acme-challenge folder
[*] Create /opt/bunkerized-nginx/plugins folder
[*] Set permissions on files and folders
[!] **Error from command : chmod 750 /opt/bunkerized-nginx/jobs/certbot-*.py
chmod: cannot access '/opt/bunkerized-nginx/jobs/certbot-*.py': No such file or directory**
[*] Cleaning /tmp/bunkerized-nginx

**Comment by fl0ppy-d1sk** [comment]
Hello @circa1741, fixed in the last 1.4.0 version.
