### ISSUE TITLE
[FEATURE] Proxy protocol

### ISSUE THREAD

**Issue by MaximilianGaedig** [bunkerity/bunkerweb#228]
**What's needed and why ?**
Proxy protocol, I use proxy protocol for my reverse proxy configurations and would like to use it as well in bunkerized, it should not be hard to implement

**Implementations ideas (optional)**
Just an env variable that enables it and another one for the IP, just like   "PROXY_REAL_IP": "yes", "PROXY_REAL_IP_FROM": "{{ ip }}",

**Comment by jdqw210** [comment]
I would also like to see this implemented, for use with frp reverse proxy: https://github.com/fatedier/frp

**Comment by MaximilianGaedig** [comment]
> I would also like to see this implemented, for use with frp reverse proxy: https://github.com/fatedier/frp

That’s the point of proxy protocol, it connects proxies so frp should work, if you don’t want to wait you can merge my PR or just use my repo

**Comment by fl0ppy-d1sk** [comment]
Hello @MaximilianGaedig and @rmrf-sl4sh, Proxy protocol is now supported (more info [here](https://docs.bunkerweb.io/1.4/quickstart-guide/#proxy-protocol) and [here](https://docs.bunkerweb.io/1.4/settings/#real-ip))
