### ISSUE TITLE
[BUG] GoAccess log format error

### ISSUE THREAD

**Issue by D3vl0per** [bunkerity/bunkerweb#229]
**Description**
GoAccess can't recognize the current by default log format.

**How to reproduce**
`goaccess access.log`

**Logs**
> Token 'example.com' doesn't match specifier '%h' 

**Solution (maybe)**
`goaccess access.log --log-format='%v %h - %^ [%d:%t %^] "%r" %s %b "%R" "%u"' --date-format='%d/%b/%Y' --time-format='%H:%M:%S' `

**Comment by zanderisrael** [comment]
Looks like there are logs from bunkerized mixed in... it breaks the log format

**Comment by fl0ppy-d1sk** [comment]
Hello @D3vl0per and @zanderisrael,

I know it's an old issue but you can configure your own log format with the `LOG_FORMAT` setting (more info [here](https://docs.bunkerweb.io/1.4/settings/#global-settings)).

**Comment by zanderisrael** [comment]
The issue is not with the format, its the ban messages, and mod-security logs that break format.On 7 Oct 2022, at 15:58, Florian Pitance ***@***.***> wrote:﻿
Hello @D3vl0per and @zanderisrael,
I know it's an old issue but you can configure your own log format with the LOG_FORMAT setting (more info here).

**Comment by fl0ppy-d1sk** [comment]
Hello @zanderisrael,

Ok, I understand. What about filtering the logs and passing it as input to goaccess : 
```
grep '^[a-zA-Z0-9\-\.]* ' access.log | goaccess -
```

**Comment by zanderisrael** [comment]
that’s what I ended up doing… its not ideal tho.

**Comment by fl0ppy-d1sk** [comment]
You're right. Opened #321 for a generic "logging" feature but it will be postponed to the next major release (1.5).

**Comment by zanderisrael** [comment]
Great thanks :)
