### ISSUE TITLE
Bunkerized-nginx still maintained?

### ISSUE THREAD

**Issue by mwester117** [bunkerity/bunkerweb#236]
Hello,

is this project still maintained? The last commit and docker built was on 24 Oct 2021. There are several Issues and Pull requests not answered for a long time. 
Some of them are even security enhancements. 

Will this project still be maintained and updated in the future?

Cheers!

**Comment by fl0ppy-d1sk** [comment]
Hello @mwester117,

We have decided to focus exclusively on the new version which should be released by the end of april. I'm sorry for the delay but I'm pretty sure everyone will like that upgrade !

Keeping this issue open in case someone else has the same question.

**Comment by mwester117** [comment]
Hello @fl0ppy-d1sk,

thanks for your reply. This is good news.
 It would be better for a security product to be updated more frequently in the future. Were there any announcements about that?

However, I am excited to see what the new version will bring!

**Comment by baradhili** [comment]
Just like to mention.. the signing key for the repo is failing.. looks like your signing key has changed, but the asc is an older one?

**Comment by baradhili** [comment]
@fl0ppy-d1sk do you want some help?

**Comment by cocoonkid** [comment]
@fl0ppy-d1sk  Looking foward to this!  Absolutely loving your work!

**Comment by mwester117** [comment]
Hello @fl0ppy-d1sk,

can you give us a status update?

**Comment by dimon222** [comment]
Its end of May, and there's nothing. Is repository now sunset fully?

**Comment by borestad** [comment]
Seems to be alive now :)

**Comment by cocoonkid** [comment]
wohooooo!!

> Its end of May, and there's nothing. Is repository now sunset fully?

what about checking discord and training patience :-)

**Comment by baradhili** [comment]
guess we can close this?
