### ISSUE TITLE
more_set_headers don't work

### ISSUE THREAD

**Issue by shizzgar** [bunkerity/bunkerweb#239]
I think because of that:
https://github.com/bunkerity/bunkerized-nginx/blob/f0f1c79d40d3d8a560d512c8f3c1e990bcfb0c9d/confs/site/custom-headers.conf#L3
Here should be "more_set_header**s**"

I tried to add custom header TeSt:TeSt to CUSTOM_HEADER env
But nginx gives me the next output:

myreverse_1  | [2022-04-08 14:21:07] entrypoint - INFO - starting bunkerized-nginx ...
myreverse_1  | [2022-04-08 14:21:07] entrypoint - INFO - configuring bunkerized-nginx ...
myreverse_1  | [2022-04-08 14:21:08] entrypoint - INFO - generator output : [*] Generation done !
myreverse_1  | [2022-04-08 14:21:08] job - INFO - executing job self-signed-cert
myreverse_1  | [2022-04-08 14:21:08] self-signed-cert - INFO - generated certificate /etc/nginx/default-cert.pem with private key /etc/nginx/default-key.pem
myreverse_1  | [2022-04-08 14:21:08] job - INFO - job self-signed-cert successfully executed
myreverse_1  | [2022-04-08 14:21:08] job - INFO - skipped reload operation because it's not needed (job = self-signed-cert)
myreverse_1  | [2022-04-08 14:21:09] job - INFO - executing job user-agents
myreverse_1  | [2022-04-08 14:21:09] job - INFO - job user-agents successfully executed
myreverse_1  | [2022-04-08 14:21:09] job - INFO - skipped reload operation because it's not needed (job = user-agents)
myreverse_1  | [2022-04-08 14:21:09] job - INFO - executing job referrers
myreverse_1  | [2022-04-08 14:21:09] job - INFO - job referrers successfully executed
myreverse_1  | [2022-04-08 14:21:09] job - INFO - skipped reload operation because it's not needed (job = referrers)
myreverse_1  | [2022-04-08 14:21:09] job - INFO - executing job exit-nodes
myreverse_1  | [2022-04-08 14:21:09] job - INFO - job exit-nodes successfully executed
myreverse_1  | [2022-04-08 14:21:09] job - INFO - skipped reload operation because it's not needed (job = exit-nodes)
myreverse_1  | [2022-04-08 14:21:10] job - INFO - executing job proxies
myreverse_1  | [2022-04-08 14:21:10] job - INFO - job proxies successfully executed
myreverse_1  | [2022-04-08 14:21:10] job - INFO - skipped reload operation because it's not needed (job = proxies)
myreverse_1  | [2022-04-08 14:21:10] job - INFO - executing job abusers
myreverse_1  | [2022-04-08 14:21:10] job - INFO - job abusers successfully executed
myreverse_1  | [2022-04-08 14:21:10] job - INFO - skipped reload operation because it's not needed (job = abusers)
myreverse_1  | [2022-04-08 14:21:10] entrypoint - INFO - running nginx ...
myreverse_1  | 2022/04/08 14:21:10 [emerg] 88#88: unknown directive "more_set_header" in /etc/nginx/custom-headers.conf:89
myreverse_1  | nginx: [emerg] unknown directive "more_set_header" in /etc/nginx/custom-headers.conf:89
myreverse_1  | [2022-04-08 14:21:10] entrypoint - INFO - bunkerized-nginx stopped

**Comment by fl0ppy-d1sk** [comment]
Nice catch ! It should be fixed in the last 1.4.0 version. Thanks.
