### ISSUE TITLE
[BUG] apt repository doesn't exist

### ISSUE THREAD

**Issue by Venem** [bunkerity/bunkerweb#245]
Hello, I'm trying to install bunkerweb using the instructions for ubuntu at https://docs.bunkerweb.io/1.4/integrations/#linux.

It's managed to add the repo but upon executing `apt update`, this is spat out:

```
Get:1 http://security.ubuntu.com/ubuntu jammy-security InRelease [110 kB]
Hit:2 https://download.docker.com/linux/ubuntu impish InRelease
Hit:3 http://nova.clouds.archive.ubuntu.com/ubuntu jammy InRelease
Get:4 http://nova.clouds.archive.ubuntu.com/ubuntu jammy-updates InRelease [109 kB]
Get:5 http://nova.clouds.archive.ubuntu.com/ubuntu jammy-backports InRelease [99.8 kB]
Ign:6 https://packagecloud.io/bunkerity/bunkerweb/ubuntu jammy InRelease
Err:8 https://packagecloud.io/bunkerity/bunkerweb/ubuntu jammy Release
  404  Not Found [IP: 54.241.1.205 443]
Hit:7 https://packagecloud.io/crowdsec/crowdsec/ubuntu jammy InRelease
Reading package lists... Done
E: The repository 'https://packagecloud.io/bunkerity/bunkerweb/ubuntu jammy Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

Visiting the [URL](https://packagecloud.io/bunkerity/bunkerweb/ubuntu) suggests that the repo doesn't exist:

![image](https://user-images.githubusercontent.com/86153674/171908526-6b8639c9-fd9a-40ea-a174-000b156ef2f2.png)

**Comment by Venem** [comment]
The repository is empty:
![image](https://user-images.githubusercontent.com/86153674/171908736-7c2b0a12-08bd-4b13-b5f6-ba8961533970.png)

I think I just got unlucky with my timing and the packages are being uploaded right now. Will report back if I see any change

**Comment by TheophileDiot** [comment]
> Hello, I'm trying to install bunkerweb using the instructions for ubuntu at https://docs.bunkerweb.io/1.4/integrations/#linux.
> 
> It's managed to add the repo but upon executing `apt update`, this is spat out:
> 
> ```
> Get:1 http://security.ubuntu.com/ubuntu jammy-security InRelease [110 kB]
> Hit:2 https://download.docker.com/linux/ubuntu impish InRelease
> Hit:3 http://nova.clouds.archive.ubuntu.com/ubuntu jammy InRelease
> Get:4 http://nova.clouds.archive.ubuntu.com/ubuntu jammy-updates InRelease [109 kB]
> Get:5 http://nova.clouds.archive.ubuntu.com/ubuntu jammy-backports InRelease [99.8 kB]
> Ign:6 https://packagecloud.io/bunkerity/bunkerweb/ubuntu jammy InRelease
> Err:8 https://packagecloud.io/bunkerity/bunkerweb/ubuntu jammy Release
>   404  Not Found [IP: 54.241.1.205 443]
> Hit:7 https://packagecloud.io/crowdsec/crowdsec/ubuntu jammy InRelease
> Reading package lists... Done
> E: The repository 'https://packagecloud.io/bunkerity/bunkerweb/ubuntu jammy Release' does not have a Release file.
> N: Updating from such a repository can't be done securely, and is therefore disabled by default.
> N: See apt-secure(8) manpage for repository creation and user configuration details.
> ```
> 
> Visiting the [URL](https://packagecloud.io/bunkerity/bunkerweb/ubuntu) suggests that the repo doesn't exist:
> 
> ![image](https://user-images.githubusercontent.com/86153674/171908526-6b8639c9-fd9a-40ea-a174-000b156ef2f2.png)

The Linux packages are being build, try again in an hour. 😁

**Comment by Venem** [comment]
I guess I was too eager lol. Can't wait to use it btw :100:

**Comment by TheophileDiot** [comment]
> I guess I was too eager lol. Can't wait to use it btw 💯

Let’s keep this issue open in case someone else as the same issue 😁

**Comment by Venem** [comment]
> Let’s keep this issue open in case someone else as the same issue grin
too eager again...

**Comment by fl0ppy-d1sk** [comment]
Hello @Venem, it should be fixed now.

**Comment by Venem** [comment]
Thank you!
