### ISSUE TITLE
[BUG] Dependency issues on Ubuntu Server

### ISSUE THREAD

**Issue by Venem** [bunkerity/bunkerweb#250]
Hi, I'm trying to install bunkerweb on my 22.04 Ubuntu server but I've run into some issues with the dependencies.

```
The following packages have unmet dependencies:
 bunkerweb : Depends: nginx (>= 1.20.2)
```

After adding the official nginx repository, which provides a version newer than 1.20.2, I ran into more issues with nginx's modules. `sudo systemctl status nginx` outputs the following:

```
× nginx.service - nginx - high performance web server
     Loaded: loaded (/lib/systemd/system/nginx.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Fri 2022-06-03 16:24:20 UTC; 1 day 16h ago
       Docs: https://nginx.org/en/docs/
        CPU: 3ms

Jun 03 16:24:20 vps-d717cb02 nginx[3097]: nginx: [emerg] module "/usr/lib/nginx/modules/ngx_http_cookie_flag_filter_module.so" version 1021006 instead of 1018000 in /etc/nginx/nginx.conf:4
Jun 03 16:24:20 vps-d717cb02 systemd[1]: Starting A high performance web server and a reverse proxy server...
Jun 03 16:24:20 vps-d717cb02 nginx[3097]: nginx: configuration file /etc/nginx/nginx.conf test failed
Jun 03 16:24:20 vps-d717cb02 systemd[1]: nginx.service: Control process exited, code=exited, status=1/FAILURE
Jun 03 16:24:20 vps-d717cb02 systemd[1]: nginx.service: Failed with result 'exit-code'.
Jun 03 16:24:20 vps-d717cb02 systemd[1]: Failed to start A high performance web server and a reverse proxy server.
```

The issue seems to be the ngx_http_cookie_flag_filter module. I tried to purge nginx in case the module didn't get installed with the official nginx but that didn't help.

Without bunkerweb, both nginx versions work. They don't seem to have any modules installed by default. I'm assuming that I need a different version of `ngx_http_cookie_flag_filter_module.so` but I couldn't find a package for it.

**Comment by Venem** [comment]
I should add, I was having this issue a few days ago when I tried to install the old version (bunkerized-nginx)

**Comment by fl0ppy-d1sk** [comment]
Can you try to force installing 1.20.2 ? Because 1.22.0 is not supported.

Once NGINX repository has been added you should be able to do it with following command : 
```shell
 apt install -y nginx=1.20.2-1~jammy
```

**Comment by Venem** [comment]
That seems to work, thanks. How do I make this viable for a production environment though? I assume nginx would upgrade itself upon me running `sudo apt upgrade` and making apt ignore it would cause important upgrades to be ignored. Is there any way I can tie bunkerweb with the nginx versions?

**Comment by Venem** [comment]
Also is it possible to use bunkerweb with nginx 1.18.0 (from ubuntu repositories) or is it flat out incompatible? I need to be able to use `libnginx-mod-http-perl` (for my xmpp server file uploads - [link](https://github.com/weiss/ngx_http_upload)) and that's not compatible with any version other than 1.18.0.

**Comment by fl0ppy-d1sk** [comment]
Hello @Venem,

BW is not compatible with NGINX 1.18.0 unless you hack it yourself. But maybe you can compile by hand the needed modules as dynamic modules for NGINX 1.20.2 ?

By the way if you want to stick with your installed NGINX and BunkerWeb versions : 
```shell
sudo apt-mark hold nginx bunkerweb
```

**Comment by fl0ppy-d1sk** [comment]
Hello @Venem,

Documentation has been updated with specific version, version "sticking" and some information on how to compile BW from source code.
