### ISSUE TITLE
[FEATURE] Temporary fix to systemd service

### ISSUE THREAD

**Issue by Venem** [bunkerity/bunkerweb#253]
The systemd service currently contains a `Documentation=Coming Soon` line. This causes the service to not work since systemd tries to connect to the URL. Until the documentation is made available, could this line either be removed or commented out so that bunkerweb will work. (I have sorted it out but other people might not be able to see the cause of the problem)

**Comment by fl0ppy-d1sk** [comment]
Hello @Venem,

Just deployed a quick fix to edit that link in the unit file and also edited the [Linux section of the docs](https://docs.bunkerweb.io/1.4/integrations/#linux) to add clear instructions on how to install NGINX 1.20.2.

Thanks for your feedback !
