### ISSUE TITLE
[BUG] Docker-compose can't pull image of bunkerweb

### ISSUE THREAD

**Issue by DimitryVo** [bunkerity/bunkerweb#254]
**Description**
Docker-compose can't pull image of bunkerweb on Ubuntu/Debian

**How to reproduce**
root:/home/bunker/bunkerweb/examples/wordpress# docker-compose up
Creating network "wordpress_default" with the default driver
Pulling mybunker (bunkerity/bunkerweb:1.4.0)...
1.4.0: Pulling from bunkerity/bunkerweb
ERROR: no matching manifest for linux/amd64 in the manifest list entries

**Logs**
?

**Comment by fl0ppy-d1sk** [comment]
Hello @DimitryVo,

I'm working on it. Something is wrong with the CI/CD and only ARM images are present. Will keep you updated.

**Comment by fl0ppy-d1sk** [comment]
Hello @DimitryVo,

It should be fixed now :
![image](https://user-images.githubusercontent.com/54334437/172313616-92ac21cb-124a-441b-973d-6e09769553a9.png)

Don't hesitate to open a new issue if needed.
