### ISSUE TITLE
[DOCUMENTATION] Upgrade

### ISSUE THREAD

**Issue by fl0ppy-d1sk** [bunkerity/bunkerweb#260]
We need to add upgrade howto and best practices for each integration in the documentation.

**Comment by chrismade** [comment]
+1 for this DOC request

I tried to upgrade yesterday from 1.4.3 to 1.4.4 and found /opt/bunkerweb completely removed - as *ALL* files (config files like variables.env and ui.env + code + customer data in www ) goes under this folder finding it removed is the worst case.

users should be advised at least to backup any config variables.env and ui.env and data under www before even thinking of backup -

having that said ... a new install (in my case: linux on debian buster) even after "apt remove bunkerweb" does not work either with error
Failed to enable unit: File /etc/systemd/system/bunkerweb.service already exists.
or
Failed to enable unit: File /etc/systemd/system/bunkerweb.service missing

hence a detailed description how to update bunkerweb properly is needed
