### ISSUE TITLE
[FEATURE] make MAX_CLIENT_SIZE auto editing modsecurity SecRequestBodyLimit

### ISSUE THREAD

**Issue by thelittlefireman** [bunkerity/bunkerweb#295]
**What's needed and why ?**
Like what's done for ALLOWED_METHODS, settings the MAX_CLIENT_SIZE auto edit modecurity config ==> SecRequestBodyLimit XXX

**Comment by fl0ppy-d1sk** [comment]
Hello @thelittlefireman,

Feature added in the last [v1.4.4 release](https://github.com/bunkerity/bunkerweb/releases/tag/v1.4.4).
