### ISSUE TITLE
[DOC] Production Setup Steps

### ISSUE THREAD

**Issue by 0FiRE0** [bunkerity/bunkerweb#301]
**Description**
Currently, upon start up of the service, the "myui" is showing a warning that the server setup should be used for Development Environment and it is not recommended for Production Environment, as per the below screenshot:
![image](https://user-images.githubusercontent.com/19993814/191612575-6e47b903-807a-4433-9152-a9dff40b3a40.png)

**Proposal (optional)**
Please include the recommended steps and procedures for Production Setup.

**Comment by fl0ppy-d1sk** [comment]
Hello @0FiRE0,

It should be fixed in the last [v1.4.4 release](https://github.com/bunkerity/bunkerweb/releases/tag/v1.4.4) : we set production mode by default.
