### ISSUE TITLE
[FEATURE] Have a specific defined order for the core plugins + add docs about it

### ISSUE THREAD

**Issue by TheophileDiot** [bunkerity/bunkerweb#306]
**What's needed and why ?**
Some core plugins have the same order number, it would be better if we had a defined order so we know the exact pipeline of the security features.

**Implementations ideas (optional)**
Have a defined order for the existing core plugins and throw an error if two of them have the same order value.

**Comment by fl0ppy-d1sk** [comment]
Done in the last [v1.4.4 release](https://github.com/bunkerity/bunkerweb/releases/tag/v1.4.4).
