### ISSUE TITLE
[FEATURE] Upgrade dependencies

### ISSUE THREAD

**Issue by fl0ppy-d1sk** [bunkerity/bunkerweb#319]
Upgrade the dependencies : 
- ModSecurity
- ModSecurity-nginx
- OWASP CRS
- LUA dependencies
- PYTHON dependencies

We also need to add a way to automatically check and test new versions of (some) dependencies like the Python ones (cc @TheophileDiot).

**Comment by EricDriussi** [comment]
Hi there! May I ask what versions of those dependencies are used?
I've looked around for a while but can't seem to find the information.

It would help a lot when troubleshooting :smiley:

**Comment by TheophileDiot** [comment]
Hi @EricDriussi 
Here are the current versions :

ModSecurity => v3.0.4
ModSecurity-nginx => v1.0.2
OWASP CRS => v3.3.2

The LUA deps and others are listed in this file :
https://github.com/bunkerity/bunkerweb/blob/master/deps/clone.sh

And the python deps are in theses two files :
https://github.com/bunkerity/bunkerweb/blob/master/deps/requirements.in
https://github.com/bunkerity/bunkerweb/blob/master/ui/requirements.txt

**Comment by EricDriussi** [comment]
Thank you very much!!

**Comment by alexanderadam** [comment]
**FYI:** [ModSecurity => v3.0.9 apparently also doesn't suffer from the well-known memory leak](https://github.com/SpiderLabs/ModSecurity/issues/2848#issuecomment-1527608284) any more.

**Comment by fl0ppy-d1sk** [comment]
We updated many dependencies in the last [v1.5.0-beta release](https://github.com/bunkerity/bunkerweb/releases/tag/v1.5.0-beta).

Dependabot setup and various helpers will also help us to keep everything up-to-date.
