### ISSUE TITLE
[BUG] my ui is not starting for some reason...

### ISSUE THREAD

**Issue by kingmaj0r** [bunkerity/bunkerweb#320]
**Description**
Concise description of what you're trying to do, the expected behavior and the current bug.
im trying to host bunkerui through docker but my ui wont start
**How to reproduce**
Give steps on how to reproduce the bug (e.g. : commands, yaml, configs, tests, environment, version, ...).
i just start the server and it gives me an error
**Logs**
The logs generated by BunkerWeb. **DON'T FORGET TO REMOVE PRIVATE DATA LIKE IP ADDRESSES !**
https://privatebin.fr/?2f1ac941080671ce#E91JmBC46SL1GNTyJSoo4F2pamppXYeGgczJNrS9BunW

**Comment by fl0ppy-d1sk** [comment]
Hello @kingmaj0r,

Can you share your compose file or docker commands please ?

**Comment by kingmaj0r** [comment]
sure

**Comment by kingmaj0r** [comment]
version: '3'

services:
  mybunker:
    image: bunkerity/bunkerweb:1.4.3
    ports:
      - 1010:8080
      - 1011:8443
    volumes:
      - bw-data:/data
      - bw-confs:/etc/nginx
    labels:
      - "bunkerweb.UI"
    environment:
      - SERVER_NAME=domain
      - MULTISITE=yes
      - HTTP_PORT=1011
      - HTTPS_PORT=1010
      - GENERATE_SELF_SIGNED_SSL
      - SELF_SIGNED_SSL_SUBJ=/CN=domain
      - REDIRECT_HTTP_TO_HTTPS=yes
      - EMAIL_LETS_ENCRYPT=KingMaj0r@hotmail.com
      - DISABLE_DEFAULT_SERVER=yes
      - USE_CLIENT_CACHE=yes
      - USE_GZIP=yes
      - API_WHITELIST_IP=ip/8 ip/24
      - domain_AUTH_BASIC_USER=user
      - domain_AUTH_BASIC_PASSWORD=KingMaj0r###
      - domain_AUTH_BASIC_PASSWORD_REMOTE_PHP_PATH=/run/php/php8.1-fpm.sock
      - domain_AUTH_BASIC_PASSWORD_USE_REVERSE_PROXY=yes
      - domain_AUTH_BASIC_PASSWORD_REVERSE_PROXY_INTERCEPT_ERRORS=no
      - domain_AUTH_BASIC_PASSWORD_USE_UI=yes
      - domain_AUTH_BASIC_PASSWORD_REVERSE_PROXY_URL=/
      - domain_AUTH_BASIC_PASSWORD_REVERSE_PROXY_HOST=http://myui:7000/
      - domain_AUTH_BASIC_PASSWORD_REVERSE_PROXY_HEADERS=X-Script-Name /
      - domain_AUTH_BASIC_PASSWORD_LIMIT_REQ_URL=/plugins/upload
      - domain_AUTH_BASIC_PASSWORD_LIMIT_REQ_RATE=4r/s
      - domain_AUTH_BASIC_PASSWORD_LIMIT_REQ_URL_1=/logs
      - domain_AUTH_BASIC_PASSWORD_LIMIT_REQ_RATE_1=4r/s
    networks:
      - bw-services
      - bw-ui

  myui:
    image: bunkerity/bunkerweb-ui:1.4.3
    depends_on:
      - mydocker
    networks:
      - bw-ui
      - bw-docker
    volumes:
      - bw-data:/data
      - bw-confs:/etc/nginx
    environment:
      - DOCKER_HOST=tcp://mydocker:2375
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=KingMaj0r###
      - ABSOLUTE_URI=https://firewall.creeperealm.net/

  mydocker:
    image: tecnativa/docker-socket-proxy
    environment:
      - CONTAINERS=1
    networks:
      - bw-docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  bw-data:
  bw-confs:

networks:
  bw-services:
    name: bw-services
  bw-ui:
    ipam:
      driver: default
      config:
        - subnet: ip/24
  bw-docker:
    name: bw-docker

**Comment by kingmaj0r** [comment]
of course "domain/ip" is not my actual domain/ip

**Comment by kingmaj0r** [comment]
any update?
