### ISSUE TITLE
[FEATURE] Integrate crowdsec

### ISSUE THREAD

**Issue by lordraiden** [bunkerity/bunkerweb#331]
Integrate crowdsec project in the stack
https://github.com/crowdsecurity/crowdsec
It will be another useful security layer.

**Comment by TheophileDiot** [comment]
Hi, thank you for your suggestion !
There actually is a plugin for that :
[Crowdsec plugin](https://github.com/bunkerity/bunkerweb-plugins/tree/main/crowdsec)
