### ISSUE TITLE
[BUG] Let'encrypt renewal error

### ISSUE THREAD

**Issue by thelittlefireman** [bunkerity/bunkerweb#335]
**Description**
every time bunkerweb try to renew a certificate it's face to an issue and renew doesn't work.
bunkerweb: 1.4.3, docker

**How to reproduce**
Start bunkerweb and wait for job renewal

**Logs**
```
Failed to renew certificate dashboard.XXXXXX with error: Unable to find manual-auth-hook command /opt/bunkerized-nginx/jobs/certbot-auth.py in the PATH.
(PATH is /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```

**Comment by TheophileDiot** [comment]
Hello @thelittlefireman 
 
This should be fixed in the last [1.5.0 release](https://github.com/bunkerity/bunkerweb/tree/v1.5.0).

Thanks again !

If the error reoccur, feel free to open the issue back
