### ISSUE TITLE
[BUG] bwcli unban ... // invalid syntax

### ISSUE THREAD

**Issue by jonathangeller** [bunkerity/bunkerweb#359]
1.4.4
Tested on Ubuntu Jammy, Debian bulleseye, installation version and docker. Tried in standalong and autoconf, same error.
When trying to unban, or even just type bwcli, an invalid syntax error:

```
Traceback (most recent call last):
  File "/opt/bunkerweb/cli/main.py", line 12, in <module>
    from CLI import CLI
  File "/opt/bunkerweb/cli/CLI.py", line 107
    ret, resp = self._send_to_apis("GET", "/bans", response=True) :
                                                                  ^
SyntaxError: invalid syntax
```

Worked in 1.4.2 and 1.4.3 (bunkerweb) cli.py added lines in 1.4.4 that's causing error.
(bunkerweb-autoconf) another story...

**Comment by fl0ppy-d1sk** [comment]
Hello @jonathangeller,

It should be fixed in the [v1.4.5 release](https://github.com/bunkerity/bunkerweb/releases/tag/v1.4.5).
