### ISSUE TITLE
docker-compose boilerplate with bunkerized stack

### ISSUE THREAD

**Issue by ghost** [bunkerity/bunkerweb#36]
Hi @bunkerity ,

Hope you are all well !

Is it possible to create a demo repository with the current bunkerized docker images for a demo with Wordpress or Prestashop ?

That would be awesome for setting up real-world use cases.

I started 11 months ago a project call prestadock but my approach is not as good as yours :-)
- https://github.com/lucmichalski/prestadock
- https://github.com/x0rzkov/wordpress-nginx-docker

I just added docker-sync files as extra feature.

Ps. It would be also interesting to add secured backup strategies with Percona toolkits.

Thanks for any inputs or insights about these questions.

Cheers,
X

**Comment by bunkerity** [comment]
Hi @lucmichalski, thanks for your suggestion.

ATM, only the bunkerized-nginx image is officialy released. There is still some work to do on the others.
We will look into this projects to see if we can integrate some of your features.

Automatic backup is a good idea espcially for databases (even for web files ?).

Let's keep this open as a reminder.

**Comment by lucmichalski** [comment]
I ll recommend percona for hot backups !

Refs:
- https://hub.docker.com/_/percona
- https://github.com/pasientskyhosting/ps-mysql-toolkit

Do you need some help for building more bunkerized images ?

**Comment by TheophileDiot** [comment]
Hi @lucmichalski there are examples with prestashop and wordpress available now :smile:
