### ISSUE TITLE
[FEATURE] Intercept specifics error codes

### ISSUE THREAD

**Issue by quentin-fougereau** [bunkerity/bunkerweb#379]
**What's needed and why ?**
 It would be nice if we could keep REVERSE_PROXY_INTERCEPT_ERRORS enable with the ability to choose which error code needs a redirection or not.
For example, I would like that Bunkwerweb intercepts errors when a 403 occurs, but let the backend response going back to the client when a 401 is triggered. 

Currently, when REVERSE_PROXY_INTERCEPT_ERRORS is enable all the following error code are intecepted by default : "400", "401", "403", "404", "405", "413", "429", "500", "501", "502", "503", "504".

**Implementations ideas (optional)**
We could have a setting like REVERSE_PROXY_INTERCEPT_ERROR_CODES which take a list or error codes separated with whitespace.
For example : REVERSE_PROXY_INTERCEPT_ERROR_CODES=403 404 502

**Comment by fl0ppy-d1sk** [comment]
Hello @quentin-fougereau,

Your code has been integrated into the [v1.4.6 release](https://github.com/bunkerity/bunkerweb/releases/tag/v1.4.6). Thanks for your contribution ! 💯
