### ISSUE TITLE
Does't delete service if you have two domain configured

### ISSUE THREAD

**Issue by andyoulovexy** [bunkerity/bunkerweb#386]
![image](https://user-images.githubusercontent.com/38940994/207211644-f4541a42-86c9-41ed-a83d-e7604221ab1e.png)
How to delete it or reconfigure it?

**Comment by TheophileDiot** [comment]
Hi, indeed this is a bug, thank you for reporting it, we'll fix it asap

**Comment by fl0ppy-d1sk** [comment]
Hello @andyoulovexy,

It should be fixed in the [v1.4.6 release](https://github.com/bunkerity/bunkerweb/releases/tag/v1.4.6).
