### ISSUE TITLE
[BUG]certificate has expired

### ISSUE THREAD

**Issue by andyoulovexy** [bunkerity/bunkerweb#399]
![image](https://user-images.githubusercontent.com/38940994/210138280-f2fbf361-c9d6-4912-802f-866fa491bea7.png)

my bunkerweb error
![image](https://user-images.githubusercontent.com/38940994/210138319-bca44609-6a02-4ee8-b378-6e67ebda62ad.png)
![image](https://user-images.githubusercontent.com/38940994/210138330-e7ae2683-be3a-410a-b0d4-4b413bd01be2.png)

**Comment by TheophileDiot** [comment]
Hi @andyoulovexy, are you using some kind of country whitelisting or blacklisting ?

**Comment by fl0ppy-d1sk** [comment]
It was related to our own infrastructure. It should be fixed now.
