### ISSUE TITLE
Modsecurity Not blocking Post Request Attacks

### ISSUE THREAD

**Issue by navein-kumar** [bunkerity/bunkerweb#400]
i have installed bunkerweb using docker and enabled modsecurity and web app connected via reverse proxy.i executed script via GET request(<script>alert(1)</script>) getting blocked by modsecurity waf. similarly,i executed the same script in POST body parameter but modsecurity is not blocked.is anyone faced this issues,kindly help this out to resolve.

my docker config details below

docker network create bw-services && \

docker volume create bw-data && \

docker run -d \
       --name mybunker \
       --network bw-services \
       -p 80:8080 \
       -p 443:8443 \
       -v bw-data:/data \
       -e SERVER_NAME=waf.example.in \
       -e USE_ANTIBOT=cookie \
       -e BAD_BEHAVIOR_BAN_TIME=900 \
       -e LIMIT_CONN_MAX_HTTP1=100 \
       -e 'ALLOWED_METHODS=GET|POST|HEAD|PUT|DELETE' \
       -e MAX_CLIENT_SIZE=35m \
       -e USE_REAL_IP=yes \
       -e USE_REVERSE_PROXY=yes \
       -e GENERATE_SELF_SIGNED_SSL=yes \
       -e SELF_SIGNED_SSL_SUBJ=/CN=waf.example.in/ \
       -e REVERSE_PROXY_URL=/ \
       -e 'REVERSE_PROXY_HOST=https://182.xx.xx.xx:9443' \
       bunkerity/bunkerweb:1.4.5

**Comment by TheophileDiot** [comment]
Hi, It's possible that OWASP didn't include this inside their rules

**Comment by TheophileDiot** [comment]
@navein-kumar Hi, any news on this issue ?

**Comment by naveencodesec** [comment]
@TheophileDiot We did't see any config ( https://config.bunkerweb.io/) like OWASP?

**Comment by naveencodesec** [comment]
@TheophileDiot It won't protect against POST request based attacks?

**Comment by TheophileDiot** [comment]
Looks like this isn't the case anymore
