### ISSUE TITLE
[BUG] Can't change LOG_FORMAT

### ISSUE THREAD

**Issue by Myzel394** [bunkerity/bunkerweb#412]
**Description**
When trying to edit `LOG_FORMAT`, docker-compose always tries to infer the variables as environmental variables (https://docs.bunkerweb.io/1.4/settings/#global-settings).

**How to reproduce**
1. Change `LOG_FORMAT` to e.g. `LOG_FORMAT=$host "$request"`
2. Run containers `docker-compose up -d nginx`

**Logs**
Docker shows this warning:

```
WARNING: The host variable is not set. Defaulting to a blank string.
WARNING: The request variable is not set. Defaulting to a blank string.
```

**Comment by TheophileDiot** [comment]
Hi, don't forget that in docker-compose files the `$` are variables that are defined in a `.env` file (or else) and are interpreted when building, if you want to pass `$` char sequences that are supposed to start with a `$`, you have to put it like this: `$$`

Example:
```LOG_FORMAT=$$host "$$request"```
