### ISSUE TITLE
[BUG] Can't change `CORS_ALLOW_ORIGIN`

### ISSUE THREAD

**Issue by Myzel394** [bunkerity/bunkerweb#414]
**Description**
When using `CORS_ALLOW_ORIGIN` with multiple sites, bunkerweb adds the `access-control-allow-origin` header two times. First with `access-control-allow-origin: *` and secondly with the actual value provided to the env variable.

**How to reproduce**
1. Create a new multisite configuration
2. Add to one `firstdomain.example_CORS_ALLOW_ORIGIN=https://seconddomain.example`

**Logs**
There is nothing suspicious in the logs unfortunately :/

**Comment by Myzel394** [comment]
sorry this wasn't an error from Bunkerweb but from myself

**Comment by lesensei** [comment]
@Myzel394 Could you elaborate on what you did wrong ? I'm facing the exact same problem and can't figure out where I messed my configuration :-/ Thanks !

**Comment by Myzel394** [comment]
Hey @lesensei I can't remember it correctly but afaik it was a problem with the underlying running app and not with Bunkerweb itself. So I had a Rust server running (this project https://github.com/TeamPiped/piped-proxy), which would set those headers on it's own, which would result in them being set two times (from the Rust server as well as from Bunkerweb). 

I had to first unset / remove the headers the app would set, and then add them via Bunkerweb again.
Something like this:

```
myapp.com_REMOVE_HEADERS=Server X-Powered-By X-AspNet-Version X-AspNetMvc-Version Access-Control-Allow-Origin
myapp.com_USE_CORS=yes
myapp.com_CORS_ALLOW_ORIGIN=https://myotherapp.com
```

**Comment by lesensei** [comment]
Genius ! That was it 💯 You probably saved me a bunch of hours trying to find the problem, as I really didn't expect the proxied app could have set the headers as well and that they would be relayed in addition to the headers set by bunkerweb ! You get as many thanks as hours saved on my end !
