### ISSUE TITLE
[FEATURE] Disable error pages

### ISSUE THREAD

**Issue by Myzel394** [bunkerity/bunkerweb#416]
**What's needed and why ?**
When exposing an API to the public and an error occurs, Bunkerweb always replaces it with its own error pages. Sometimes we don't want this to happen (for example when a json with details is returned back from the API).

**Implementations ideas (optional)**
Add an option like "DISABLE_ERROR_PAGES=yes" or allow disabling it with "ERRORS=no"

**Comment by TheophileDiot** [comment]
Hi, to resolve the issue, simply set the `REVERSE_PROXY_INTERCEPT_ERRORS` setting to `no`. 

In the future, kindly take some time to thoroughly read through the documentation before opening an issue. This will help avoid unnecessary confusion and save time for everyone involved. Thank you.

**Comment by Myzel394** [comment]
Hey @TheophileDiot thanks for your answer. Actually I did try to find the relevant setting in the docs, but couldnt find it.

Just as some feedback: I searched for "error", "pages", "replace" and nothing returned the setting. I would have expected such a setting to be in the "error" section.

<img width="723" alt="Screenshot 2023-02-13 at 09 10 47" src="https://user-images.githubusercontent.com/50424412/218404187-43535a67-4317-4552-81c5-506388d37f20.png">

**Comment by TheophileDiot** [comment]
Hi @Myzel394, thank you for your feedback. I did some research and found that you need to click on the "3 more on this page" link in the Settings. The titles are prioritized over the content, so this should give you access to the information you need. 😅
