### ISSUE TITLE
[BUG] 1.4.7 - Error relocating /opt/bunkerweb/modules/ngx_http_lua_module.so

### ISSUE THREAD

**Issue by Peelige** [bunkerity/bunkerweb#421]
**Description**
Docker container has updated from 1.4.6 to 1.4.7.  Container will not start.  No configuration changes.  Container starts when setting the image tags back to 1.4.6

**How to reproduce**
Update container as above

**Logs**
2023/02/28 07:12:40 [emerg] 16#16: dlopen() "/opt/bunkerweb/modules/ngx_http_lua_module.so" failed (Error relocating /opt/bunkerweb/modules/ngx_http_lua_module.so: ndk_set_var_multi_value_core: symbol not found) in /etc/nginx/nginx.conf:7
28/02/2023 7:12:40
nginx: [emerg] dlopen() "/opt/bunkerweb/modules/ngx_http_lua_module.so" failed (Error relocating /opt/bunkerweb/modules/ngx_http_lua_module.so: ndk_set_var_multi_value_core: symbol not found) in /etc/nginx/nginx.conf:7
28/02/2023 7:12:40
[2023-02-28 07:12:40] ENTRYPOINT - ℹ️ - BunkerWeb stopped

**Comment by fl0ppy-d1sk** [comment]
Hello @Peelige,

Looks like new config is not generated. Can you confirm that you have a volume mounted on `/etc/nginx` ?

**Comment by Peelige** [comment]
Hi @fl0ppy-d1sk, thanks for the quick reply.  

Yes I can confirm that the volume is mounted :  

    volumes:
      - /srv/bunkerweb/data:/data:rw
      - /srv/bunkerweb/config:/etc/nginx:rw
      - /srv/www:/data/www:rw
      - /srv/www:/opt/bunkerweb/www:rw
      
It's reading from the volume's nginx.conf as it referencing line 7 which is :  

load_module /opt/bunkerweb/modules/ngx_http_lua_module.so;

**Comment by Peelige** [comment]
Further update:  If I clear the contents of the /config folder, set bunkerweb image to 1.47 and deploy the container, the config rebuilds from scratch and container runs fine.

I then copy in the services from a backup, along with the variables.env file and restart bunkerweb, all services are operational and appear within the ui.

Not sure if there's an upgrade problem for 1.46 to 1.47 or not, but in my case the workaround closes my issue.

Thanks
