### ISSUE TITLE
Problems with proxy_protocol

### ISSUE THREAD

**Issue by andyoulovexy** [bunkerity/bunkerweb#433]
The 1.4.8 version is unstable, everything is normal at the beginning, but after running for a period of time, it can't work for no reason！！！
![image](https://user-images.githubusercontent.com/38940994/230613529-a0967010-3038-4c1e-be88-6fd4ca6d1534.png)

**Comment by fl0ppy-d1sk** [comment]
Hello @andyoulovexy,

Can you share more info please ? Like your config (I see you are using proxy protocol), more logs, integration used, ...

**Comment by TheophileDiot** [comment]
Hello @andyoulovexy,
This is like you're trying to access your website directly through BunkerWeb and without a service like `haproxy` in front.

**Comment by andyoulovexy** [comment]
> Hello @andyoulovexy,
> 
> Can you share more info please ? Like your config (I see you are using proxy protocol), more logs, integration used, ...

I have docker-compose down -v, I switched to nginx-proxy-manager temporarily, I will re-run bunkerweb sometime and provide more information

**Comment by andyoulovexy** [comment]
> Hello @andyoulovexy, This is like you're trying to access your website directly through BunkerWeb and without a service like `haproxy` in front.

I have docker-compose down -v, I switched to nginx-proxy-manager temporarily, I will re-run bunkerweb sometime and provide more information

**Comment by andyoulovexy** [comment]
> Hello @andyoulovexy, This is like you're trying to access your website directly through BunkerWeb and without a service like `haproxy` in front.

I have docker-compose down -v, I switched to nginx-proxy-manager temporarily, I will re-run bunkerweb sometime and provide more information

**Comment by TheophileDiot** [comment]
@andyoulovexy when using proxy protocol you have to put a service like `haproxy` in front of BunkerWeb otherwise the requests wont be accepted by it.

**Comment by andyoulovexy** [comment]
> @andyoulovexy when using proxy protocol you have to put a service like in front of BunkerWeb otherwise the requests wont be accepted by it.`haproxy`

Using haproxy+bunkerweb will make it more complex, just simply want to implement proxy

**Comment by TheophileDiot** [comment]
@andyoulovexy Then this is not an issue, you just have to deactivate/remove the setting `USE_PROXY_PROTOCOL` and it should work fine with just BunkerWeb.

**Comment by TheophileDiot** [comment]
@andyoulovexy I will close this issue, if you have any more question, you can reach us out on discord : https://discord.com/invite/fTf46FmtyD
