### ISSUE TITLE
Can't fetch latest blog posts in the web UI

### ISSUE THREAD

**Issue by andyoulovexy** [bunkerity/bunkerweb#435]
![image](https://user-images.githubusercontent.com/38940994/231429016-6d938922-3881-41c7-9f55-330e955148a8.png)

**Comment by andyoulovexy** [comment]
> @andyoulovexy Hi, what is the version of BunkerWeb and BunkerWeb UI are you using ? Also what are you referring to ? The problem with the blog posts ?

1.4.8

**Comment by TheophileDiot** [comment]
@andyoulovexy Could you provide us your configuration please ?

**Comment by fl0ppy-d1sk** [comment]
It should be fixed now !
