### ISSUE TITLE
[FEATURE] Add redirect feature with custom status code

### ISSUE THREAD

**Issue by stopkadr** [bunkerity/bunkerweb#463]
**What's needed and why ?**
Hi,
First, thank you for your great work! 
Current implementation (https://docs.bunkerweb.io/1.4/settings/#redirect) has status code 301 only, which uses for permanent redirects only.
I think, it would be nice to add redirect feature with custom status codes. For example, status code 302 for temporary redirects.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Redirections

Thanks.

**Comment by fl0ppy-d1sk** [comment]
Hello @stopkadr,

The 1.5.1 release now supports the `REDIRECT_TO_STATUS_CODE` setting. More info [here](https://docs.bunkerweb.io/1.5.1/settings/#redirect).
