### ISSUE TITLE
[FEATURE] Allow local URLs (file:// scheme) for whitelists (and blacklists ?)

### ISSUE THREAD

**Issue by lesensei** [bunkerity/bunkerweb#465]
**What's needed and why ?**
I like to whitelist my home Internet connection so it won't be blacklisted by Bunkerweb when I fiddle with things a tad too much. I do this by having my home-automation software publish a file with the IP when it detects a change (which happens from time to time). Problem is, the container hosting that home-automation software might not be available when Bunkerweb starts. However, the file always exists on the host's file system and it could very well be stored on a volume that would be shared with Bunkerweb's own container.
I was thus wondering if it would be conceivable to extend the way the whitelist job works at the moment with the "file://" scheme so it would be able to use local files as well. I know something close can be achieved with the WHITELIST_IP env var, but it is not dynamic and one needs to restart the container if it is changed.

**Implementations ideas (optional)**
I was thinking it might be possible to use something like [this](https://github.com/dashea/requests-file) so one could also pass local file URLs via the WHITELIST_IP_URLS env var. If you'd indeed be ok with that, I should be able to push something through a PR.

Cheers, and thanks for Bunkerweb !

**Comment by TheophileDiot** [comment]
Hi, thank you very much, this is a very good idea that we will note and take into consideration, we will probably also extend it to other plugins that do the same !

**Comment by fl0ppy-d1sk** [comment]
Hello @lesensei,

`file://` is now supported in the 1.5.1 release, enjoy !
