### ISSUE TITLE
[FEATURE] ubuntu arm builds

### ISSUE THREAD

**Issue by celevra** [bunkerity/bunkerweb#467]
Hi,

would be great if there are also arm deb packages in the repository
there seems to be allready arm builds in the docker container so hopefully it is not a big deal?

regards

**Comment by fl0ppy-d1sk** [comment]
Hello @celevra,

Thanks for your suggestion.

We are working on it, the goal is to support arm64/armhf for ubuntu/debian and aarch64 for fedora/rhel.

Will keep you updated when it's done.

**Comment by fl0ppy-d1sk** [comment]
Hello @celevra,

We now provide Linux packages for arm64/aarch64 architectures.

Feel free to test it and come back to us if you find a bug or have a suggestion.
