### ISSUE TITLE
[DOC] HTTPS_PROTOCOLS ==> SSL_PROTOCOLS

### ISSUE THREAD

**Issue by thelittlefireman** [bunkerity/bunkerweb#531]
**Description**
From 1.4.x HTTPS_PROTOCOLS has been renamed to SSL_PROTOCOLS in env variables but documentation still mention HTTPS_PROTOCOLS

`[2023-06-25 21:06:33] - GENERATOR - ⚠️  - Ignoring variable HTTPS_PROTOCOLS : variable name HTTPS_PROTOCOLS doesn't exist
`

**Proposal (optional)**
Edit this page: https://docs.bunkerweb.io/1.5.0/security-tuning/#https-ssltls

**Comment by TheophileDiot** [comment]
Hi, thank you for finding this, it'll be fixed when we will update the documentation

**Comment by fl0ppy-d1sk** [comment]
Hello @thelittlefireman,

Pushed in the 1.5.1 doc. Thanks !
