### ISSUE TITLE
[BUG] full docker to docker tls encryption cannot be used in 1.5.0

### ISSUE THREAD

**Issue by thelittlefireman** [bunkerity/bunkerweb#540]
**Description**
In bunkerweb v1.4.5 i used to map /data/letsencrypt on a home docker volume. 
It's allow me to reused certificat to do full docker to docker tls encryption. i.e. Bunkerweb/Nginx reverse proxy talk with tls with backend other dockers. 

In v1.5.0 letsencrypt folders is in /var/cache. Even if i map it as a volume It's seems to be erased or delete by scheduler. 

**How to reproduce**
Give steps on how to reproduce the bug (e.g. : commands, yaml, configs, tests, environment, version, ...).

**Logs**
The logs generated by BunkerWeb. **DON'T FORGET TO REMOVE PRIVATE DATA LIKE IP ADDRESSES !**

**Comment by TheophileDiot** [comment]
Hi @thelittlefireman, thank you for opening this issue.
Do you attach the volume where let's encrypt's data are into BunkerWeb or the scheduler ?

**Comment by TheophileDiot** [comment]
> Hi, i attach it on bunkerweb.

@thelittlefireman yeah, the thing is that when the scheduler sends the certs to BunkerWeb it erases everything, therefore you will  have to attach it to the scheduler

**Comment by TheophileDiot** [comment]
I see, with the automatically generated LE, it shouldn't be an issue

**Comment by TheophileDiot** [comment]
Hi, files inside volumes that are gonna be read by the scheduler like configurations have to have specific perms
![image](https://github.com/bunkerity/bunkerweb/assets/57175294/c9d88dc1-9465-4ce0-9924-47713cbba8c0)
