### ISSUE TITLE
Unavailability of the bunker when the client's ip address changes [BUG]

### ISSUE THREAD

**Issue by flexstat** [bunkerity/bunkerweb#556]
**Description**

It happens like this, the client connects to the bunker, everything works fine, but as soon as the client's ip address changes, for example, he starts using a vpn, the bunker stops responding to requests, and an endless chain of errors appears in the logs.

**How to reproduce**
We launch the bunker, switch to the resource, and then change the ip address and try to access the service again

**Logs**
mybunker_1      | 2023/07/09 09:31:39 [warn] 77#77: *145 [UTILS] session botsecur IP failed, destroying session, client: 60.114.288.0, server: www.example.com, request: "GET / HTTP/1.1", host: "177.22.52.0"
mybunker_1      | 2023/07/09 09:30:38 [warn] 78#78: *137 [UTILS] session botsecur IP failed, destroying session, client: 60.114.288.0, server: www.example.com, request: "GET / HTTP/1.1", host: "177.22.52.0", referrer: "http://177.22.52.0/botsecur"
mybunker_1      | 2023/07/09 09:30:38 [warn] 78#78: *137 [UTILS] session botsecur IP failed, destroying session, client: 60.114.288.0, server: www.example.com, request: "GET / HTTP/1.1", host: "177.22.52.0", referrer: "http://177.22.52.0/botsecur"
mybunker_1      | 2023/07/09 09:31:39 [warn] 77#77: *145 [UTILS] session botsecur IP failed, destroying session, client: 60.114.288.0, server: www.example.com, request: "GET / HTTP/1.1", host: "177.22.52.0"
mybunker_1      | 2023/07/09 09:30:38 [warn] 78#78: *137 [UTILS] session botsecur IP failed, destroying session, client: 60.114.288.0, server: www.example.com, request: "GET / HTTP/1.1", host: "177.22.52.0", referrer: "http://177.22.52.0/botsecur"
mybunker_1      | 2023/07/09 09:31:39 [warn] 77#77: *145 [UTILS] session botsecur IP failed, destroying session, client: 60.114.288.0, server: www.example.com, request: "GET / HTTP/1.1", host: "177.22.52.0"
mybunker_1      | 2023/07/09 09:30:38 [warn] 78#78: *137 [UTILS] session botsecur IP failed, destroying session, client: 60.114.288.0, server: www.example.com, request: "GET / HTTP/1.1", host: "177.22.52.0", referrer: "http://177.22.52.0/botsecur"
mybunker_1      | 2023/07/09 09:30:38 [warn] 78#78: *137 [UTILS] session botsecur IP failed, destroying session, client: 60.114.288.0, server: www.example.com, request: "GET / HTTP/1.1", host: "177.22.52.0", referrer: "http://177.22.52.0/botsecur"
mybunker_1      | 2023/07/09 09:30:38 [warn] 78#78: *137 [UTILS] session botsecur IP failed, destroying session, client: 60.114.288.0, server: www.example.com, request: "GET / HTTP/1.1", host: "177.22.52.0", referrer: "http://177.22.52.0/botsecur"
mybunker_1      | 2023/07/09 09:31:39 [warn] 77#77: *145 [UTILS] session botsecur IP failed, destroying session, client: 60.114.288.0, server: www.example.com, request: "GET / HTTP/1.1", host: "177.22.52.0"
mybunker_1      | 2023/07/09 09:30:38 [warn] 78#78: *137 [UTILS] session botsecur IP failed, destroying session, client: 60.114.288.0, server: www.example.com, request: "GET / HTTP/1.1", host: "177.22.52.0", referrer: "http://177.22.52.0/botsecur"
mybunker_1      | 2023/07/09 09:31:39 [warn] 77#77: *145 [UTILS] session botsecur IP failed, destroying session, client: 60.114.288.0, server: www.example.com, request: "GET / HTTP/1.1", host: "177.22.52.0"
mybunker_1      | 2023/07/09 09:30:38 [warn] 78#78: *137 [UTILS] session botsecur IP failed, destroying session, client: 60.114.288.0, server: www.example.com, request: "GET / HTTP/1.1", host: "177.22.52.0", referrer: "http://177.22.52.0/botsecur"
mybunker_1      | 2023/07/09 09:31:39 [warn] 77#77: *145 [UTILS] session botsecur IP failed, destroying session, client: 60.114.288.0, server: www.example.com, request: "GET / HTTP/1.1", host: "177.22.52.0"
mybunker_1      | 2023/07/09 09:30:38 [warn] 78#78: *137 [UTILS] session botsecur IP failed, destroying session, client: 60.114.288.0, server: www.example.com, request: "GET / HTTP/1.1", host: "177.22.52.0", referrer: "http://177.22.52.0/botsecur"
mybunker_1      | 2023/07/09 09:30:38 [warn] 78#78: *137 [UTILS] session botsecur IP failed, destroying session, client: 60.114.288.0, server: www.example.com, request: "GET / HTTP/1.1", host: "177.22.52.0", referrer: "http://177.22.52.0/botsecur"
mybunker_1      | 2023/07/09 09:31:39 [warn] 77#77: *145 [UTILS] session botsecur IP failed, destroying session, client: 60.114.288.0, server: www.example.com, request: "GET / HTTP/1.1", host: "177.22.52.0"
mybunker_1      | 2023/07/09 09:30:38 [warn] 78#78: *137 [UTILS] session botsecur IP failed, destroying session, client: 60.114.288.0, server: www.example.com, request: "GET / HTTP/1.1", host: "177.22.52.0", referrer: "http://177.22.52.0/botsecur"
mybunker_1      | 2023/07/09 09:31:39 [warn] 77#77: *145 [UTILS] session botsecur IP failed, destroying session, client: 60.114.288.0, server: www.example.com, request: "GET / HTTP/1.1", host: "177.22.52.0"
mybunker_1      | 2023/07/09 09:30:38 [warn] 78#78: *137 [UTILS] session botsecur IP failed, destroying session, client: 60.114.288.0, server: www.example.com, request: "GET / HTTP/1.1", host: "177.22.52.0", referrer: "http://177.22.52.0/botsecur"
mybunker_1      | 2023/07/09 09:30:38 [warn] 78#78: *137 [UTILS] session botsecur IP failed, destroying session, client: 60.114.288.0, server: www.example.com, request: "GET / HTTP/1.1", host: "177.22.52.0", referrer: "http://177.22.52.0/botsecur"
mybunker_1      | 2023/07/09 09:31:39 [warn] 77#77: *145 [UTILS] session botsecur IP failed, destroying session, client: 60.114.288.0, server: www.example.com, request: "GET / HTTP/1.1", host: "177.22.52.0"
mybunker_1      | 2023/07/09 09:30:38 [warn] 78#78: *137 [UTILS] session botsecur IP failed, destroying session, client: 60.114.288.0, server: www.example.com, request: "GET / HTTP/1.1", host: "177.22.52.0", referrer: "http://177.22.52.0/botsecur"

docker-compose.yml -> https://pastebin.com/69KqNdS6

**Comment by fl0ppy-d1sk** [comment]
Hello @flexstat,

I can reproduce the problem, we are working on it.

As temporary fix you can disable IP checks for sessions with `SESSIONS_CHECK_IP=no`.

**Comment by fl0ppy-d1sk** [comment]
Hello @flexstat,

We fixed it in the last 1.5.1 release. Thanks !
