### ISSUE TITLE
[BUG] 1.4.7 >> 1.5.0 Much higher CPU usage

### ISSUE THREAD

**Issue by rovingclimber** [bunkerity/bunkerweb#560]
**Description**
Comparing a fresh docker-compose install of v1.5.0 to v1.4.7 the overall CPU usage is much higher. For example on my J4125 mini-server, v1.4.7 uses maybe 1.5% CPU at idle. v1.5.0 uses, by comparison, about 7-8% CPU. This is under no-load conditions.
Looking at the individual containers, it seems that the bunkerweb-scheduler container is the main culprit, with a little help from the db container.

**How to reproduce**
Set up a fresh install using your baseline docker-compose.yaml for each version. No sites, no load.

**Logs**
I don't see anything unusual in logs, there is no "event" based on this issue it just seems to be the baseline cpu usage has increased.

**Comment by TheophileDiot** [comment]
Hi, we are aware of this issue, this will be fix in the next release. This is because of the database check that the scheduler does.

**Comment by fl0ppy-d1sk** [comment]
Hello @rovingclimber,

CPU usage by the scheduler has been reduced in the 1.5.1. Thanks for your report and don't hesitate to open a new issue if needed.
