### ISSUE TITLE
[BUG] Issue when adding new info into the config of modsecurity 

### ISSUE THREAD

**Issue by farzadha2** [bunkerity/bunkerweb#566]
**Description**
Issue when adding a new modsecurity whitelist, i have to delete the containers for it to get the config
**How to reproduce**
Give steps on how to reproduce the bug (e.g. : commands, yaml, configs, tests, environment, version, ...).
added a new config in the modsec folder and i tried to restart the container does not get the new configuration 
I have to delete the 3 containers and recreate them

**Comment by fl0ppy-d1sk** [comment]
Hello @farzadha2,

It will be fixed in the next 1.5.1 version.

**Comment by farzadha2** [comment]
thank you so much so far its working great the 1.5 only sometimes when i try to add another domain i have destroy all the containers and recreate it

**Comment by fl0ppy-d1sk** [comment]
Hello @farzadha2,

It should be fixed in the last 1.5.1 release. Don't hesitate to open a new issue if needed.
