### ISSUE TITLE
[BUG] USE_BUNKERNET=no (appears to) have no effect

### ISSUE THREAD

**Issue by chrismade** [bunkerity/bunkerweb#570]
**Description**
little to no software comes with useful documentation which WAF settings will be needed to run a certain web-based application with optimal protection - so the standard way to figure this out is activate e.g. Bunkerweb and read logfiles intensively and add rules to the configuration (trial and error method).  However, sometimes it is required to switch off bunkernet features completely to make it work like a standard reverse proxy and check if the web-based software now acts as expected in reverse proxy config.
How I understand the documentation the setting `USE_BUNKERNET=no` should do the trick.
  
**How to reproduce**
I added first a multi-site setting

```
wptest.5.77.222.111.nip.io_USE_BUNKERNET="no"

```

and tested - and then a global setting

```
USE_BUNKERNET="no"
```
I need to say I'm still on bunkernet 1.4.8 as I did not manage to migrate to 1.5.0 in a reasonable amount of time due to the various breaking changes - if it is fixed in 1.5.0 already pls state in this ticket and close

**Logs**

I used loglevel = INFO and the logfiles show no (visible) difference whether it is net to "no" or "yes" (default) - the behaviour in the upstream web application also shows no difference and certain requests are still blocked

**Note**
maybe I misunderstood the documentation and different or other settings need to be set to get the expected behavior to make bunkerweb a simple pass-thru reverse proxy - in case it is a true bug and you have to dig into the code anyway you may want to consider a 3rd setting "permissive" in addition to "yes" and "no" like we know it from SELINUX - which would allow to log what it would have blocked in full protection  - to ease the configuration process - this would be a true value add in using Bunkernet. And yes , I know it is never good to mix-up a feature request with a bug report

**Comment by fl0ppy-d1sk** [comment]
Hello @chrismade,

Looks like you are confusing Bunker**Web** and Bunker**Net** ?

I see two possibilities here : 
- Whitelisting everyone using `WHITELIST_IP=0.0.0.0/0`
- Disabling all security features listed [here](https://docs.bunkerweb.io/1.5.0/security-tuning/)

**Comment by chrismade** [comment]
thanks for the hint - indeed I mixed up bunkerweb and bunkernet (not for the first time, btw) and will give WHITELIST a try now
