### ISSUE TITLE
[BUG] Logs on the host have the wrong date time

### ISSUE THREAD

**Issue by killmasta93** [bunkerity/bunkerweb#575]
**Description**
Hi currently was checking the logs on the host and shows the date wrong, but in the container are correct the date and time 
any ideas howcome?

Thank you

**Comment by fl0ppy-d1sk** [comment]
Hello @killmasta93,

You need to set the `TZ=Europe/Paris` environment variable. You can find TZ identifiers [here](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List).

**Comment by killmasta93** [comment]
awesome that worked
