### ISSUE TITLE
[FEATURE]  bunkerweb-ui have a screen showing the requests blocked by bunkerweb

### ISSUE THREAD

**Issue by lenglet-k** [bunkerity/bunkerweb#577]
**What's needed and why ?**
currently you have to analyze the bunkerweb logs to see what is blocked. It would be interesting to have in bunkerweb-ui a screen showing the requests that pass with their states (blocked/unblocked) and the reason for the blocking

**Implementations ideas (optional)**
in bunkerwebui have a "request in transit" menu which allows a display by service of requests and their status

**Comment by fl0ppy-d1sk** [comment]
Hello @lenglet-k,

We now have a dedicated pages in the web UI to show blocked requests by BunkerWeb. Feature is available in the last 1.5.6 version. Thanks for your feedback !
