### ISSUE TITLE
[FEATURE] Have metrics on bunkerweb

### ISSUE THREAD

**Issue by lenglet-k** [bunkerity/bunkerweb#578]
**What's needed and why ?**
To monitor bunkerweb it would be interesting to have metrics in opentelemetry format in order to be able to retrieve them by tools like prometheus. This will also allow you to create dashboards and supervision alerts.

It should be understood that the metrics will have to expose information on the internal functioning of bunkerweb, for example, a metric allowing to know the number of requests blocked by service, sourceIp and by plugin:

```
bunkerweb_waf_blocked_request{service="myservice", plugin="badbehavior", sourceIp="1.1.1.1"} 10 # blocked request by service, plugin, sourceIp
bunkerweb_waf_http_request{service="myservice"} 10 # number of request
```
beware of the use of labels which can lead to high cardinality and therefore overconsumption of prometheus memory

**Implementations ideas (optional)**
have an exporter that exposes the metrics scrappable by prometheus. With that we can create a dashboard and alerts rules.

**Comment by TheophileDiot** [comment]
Hi, we have the `monitoring` PRO plugin that does it now (also the `prometheus-exporter` one)
https://www.bunkerweb.io/blog/post/bunkerweb-pro-prometheus-exporter-grafana
