### ISSUE TITLE
[FEATURE] Add popular auth system like Authentik/Authelia/Keycloak/Zitadel as plugins

### ISSUE THREAD

**Issue by BirdInFire** [bunkerity/bunkerweb#582]
**What's needed and why ?**
Having this kind of feature can let us protect the access of some more critical services behind bunker web where their own auth mechanism is not very hight (portainer, pihole, cockpit (fedora), etc...) since these kind of auth management can have many settings like password less auth, webauthn 2FA, OTP etc...

Also having this kind of advanced authentification mechanism in you product that aim to secure as much as possible by default make total sense (to add proper support for 2FA and now password less) even on app that don't support it natively (by checking the right to access in your service before redirect).

**Implementations ideas (optional)**
I see 3 possibility.

1st, you create your own auth mechanism, 
2nd, you implement in a plugin form some or all of most used FOSS (Authentik/Authelia/Keycloak are good example)
3rd, you do something else I not thanked about.

**Comment by TheophileDiot** [comment]
Hi @BirdInFire, thank you for opening this issue, we already have examples for Authelia and Authentik right here : 
- https://github.com/bunkerity/bunkerweb/tree/master/examples/authelia
- https://github.com/bunkerity/bunkerweb/tree/master/examples/authentik

If you manage to have a working example with Keycloak, we'll really appreciate it. Else we'll work on it when we have the time. Thank you for suggesting it.

**Comment by BirdInFire** [comment]
> * https://github.com/bunkerity/bunkerweb/tree/master/examples/authentik

Thanks for the file I admit I only checked in the doc website, I will check on them, but from a very fast read it's not the easiest thing to do, so this suggestion to make it more "integrated" like a plugin or so, remain.

But to be sure does these : 

# Applications
      - app1.example.com_REVERSE_PROXY_URL=/
      - app1.example.com_REVERSE_PROXY_HOST=http://app1
      - app1.example.com_REVERSE_PROXY_AUTH_REQUEST=/outpost.goauthentik.io/auth/nginx
     etc..

Mean that we must rebuild the container with docker-compose on each website or it's just example of the settings needed that can be done trough the official ui ?

**Comment by TheophileDiot** [comment]
It's just an example that you can adapt to your needs. Indeed we should maybe add a page or a field in the documentations about the examples.
