### ISSUE TITLE
[BUG] BROTLI_TYPES input box pattern attribute value is not a valid regular expression

### ISSUE THREAD

**Issue by weizhuangzhi** [bunkerity/bunkerweb#612]
**Description**
When editing the service configuration in the ui, the browser throws an error on the regex for the BROTLI_TYPES input box in the Brotli tab.

**Logs**
`Pattern attribute value ^(?! )( ?([-\w.]+/[-\w.+]+)(?!.*\2(?!.)))+$ is not a valid regular expression: Uncaught SyntaxError: Invalid regular expression: /^(?! )( ?([-\w.]+/[-\w.+]+)(?!.*\2(?!.)))+$/v: Invalid character in character class`

It should be caused by the - symbol in this [-\w.]，If use the escape character \, there will be no error.

**Comment by TheophileDiot** [comment]
Hi, thank you for opening this issue, I'll investigate this.

**Comment by fl0ppy-d1sk** [comment]
Hello @weizhuangzhi,

It should be fixed in the last [1.5.2 version](https://github.com/bunkerity/bunkerweb/releases/tag/v1.5.2). Feel free to open a new issue if needed.
