### ISSUE TITLE
[BUG] tor browser capcha Forbidden

### ISSUE THREAD

**Issue by Nikoly0072** [bunkerity/bunkerweb#625]
**Description**
Concise description of what you're trying to do, the expected behavior and the current bug.

**How to reproduce**
Give steps on how to reproduce the bug (e.g. : commands, yaml, configs, tests, environment, version, ...).

**Logs**
The logs generated by BunkerWeb. **DON'T FORGET TO REMOVE PRIVATE DATA LIKE IP ADDRESSES !**

**Comment by fl0ppy-d1sk** [comment]
Hello @Nikoly0072,

We need more info, can you fill the issue template please (description, how to reproduce and logs) ?

**Comment by TheophileDiot** [comment]
Bump @Nikoly0072
