### ISSUE TITLE
[BUG] New files added in SERVICE MANAGER will be deleted when the service is modified.

### ISSUE THREAD

**Issue by weizhuangzhi** [bunkerity/bunkerweb#638]
### What happened?

New files added in SERVICE MANAGER will be deleted when the service is modified.

### How to reproduce?

Add a service via Web UI: mysite.net
In order to add some custom configuration, add new files in SERVICE MANAGER
/etc/bunkerweb/configs/server-http/mysite.net/buffer.conf
client_header_buffer_size 4k;
proxy_buffer_size 8k;
proxy_buffers 64 4k;
proxy_busy_buffers_size 16k;

After adding it, it is still normal. Then modify the mysite.net service and save it. Then go to SERVICE MANAGER and you can see that the newly added buffer.conf file no longer exists.

### Configuration file(s) (yaml or .env)

```YAML
DNS_RESOLVERS=8.8.8.8 8.8.4.4
HTTP_PORT=80
HTTPS_PORT=443
API_LISTEN_IP=127.0.0.1
API_HTTP_PORT=7001
SERVER_NAME=bunker6.tt
MULTISITE=yes

bunker6.tt_USE_UI=yes
bunker6.tt_USE_REVERSE_PROXY=yes
bunker6.tt_REVERSE_PROXY_URL=/manage
bunker6.tt_REVERSE_PROXY_HOST=http://127.0.0.1:7000
bunker6.tt_INTERCEPTED_ERROR_CODES=400 404 405 413 429 500 501 502 503 504
```

### Relevant log output

```shell
nothing
```

### BunkerWeb version

1.5.2

### What integration are you using?

Linux

### Linux distribution (if applicable)

Fedora 38 (updated to the latest)

### Removed private data

- [X] I have removed all private data from the configuration file and the logs

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TheophileDiot** [comment]
Hi @weizhuangzhi, thank you for opening this issue, I'll try to reproduce this and let you know !

**Comment by TheophileDiot** [comment]
Hi @weizhuangzhi, turns out it was deleting the old service config folders as the scheduler thought that the service has been deleted. Now it will migrate the custom configuration files as well when changing the SERVER_NAME of a service !

**Comment by TheophileDiot** [comment]
@weizhuangzhi, turns out it was deleting the old service config folders as the scheduler thought that the service has been deleted. Now it will migrate the custom configuration files as well when changing the SERVER_NAME of a service !

**Comment by weizhuangzhi** [comment]
I checked Commit.
Is it okay to just update the ui/main.py file? I tried updating and restarting the service, but it still seemed that the configuration files I added were deleted.
Don't know what went wrong?

**Comment by weizhuangzhi** [comment]
@TheophileDiot 

Can you help me look at this problem again?

I updated the main.py file according to the above check-in, and now the situation is:
As long as you modify the service configuration (even if nothing is changed) and then save it, the newly added configuration file will disappear.
If I modify the "Server name", the newly added configuration file will be retained.

It may be that my previous description was not clear enough, and main.py may fix another problem.

This affects usage very much. Every time a configuration item is modified, the configuration file must be re-added. Since the additional configuration file is required for the website I'm using, I was hoping you could help me look into this issue again.

**Comment by weizhuangzhi** [comment]
This problem no longer exists in the dev branch, so this issue is closed.
But new problems have arisen. For details, see:

https://github.com/bunkerity/bunkerweb/issues/652#issuecomment-1751581059
