### ISSUE TITLE
[BUG] The http.conf file is not written after modifying the service configuration in the Web UI.

### ISSUE THREAD

**Issue by weizhuangzhi** [bunkerity/bunkerweb#639]
### What happened?

Add a service mysite.net in the Web UI and set up a reverse proxy and save it. Mysite.net can be accessed.

Modify the configuration, set Activate DNSBL to false and save, mysite.net cannot be accessed.
Re-modify the configuration, set Activate DNSBL to true and save, so mysite.net can be accessed.

I'm not sure if this is unique to the Activate DNSBL setting, but modifying the Activate DNSBL option reproduced the issue for me.

### How to reproduce?

I compared the files in the /etc/nginx directory before and after the settings, and found that when the /etc/nginx/http.conf file was inaccessible, the content of the /etc/nginx/http.conf file was missing at the end `include /etc/nginx/mysite.net/server.conf;`

### Configuration file(s) (yaml or .env)

```YAML
DNS_RESOLVERS=8.8.8.8 8.8.4.4
HTTP_PORT=80
HTTPS_PORT=443
API_LISTEN_IP=127.0.0.1
API_HTTP_PORT=7001
SERVER_NAME=bunker6.tt
MULTISITE=yes

bunker6.tt_USE_UI=yes
bunker6.tt_USE_REVERSE_PROXY=yes
bunker6.tt_REVERSE_PROXY_URL=/manage
bunker6.tt_REVERSE_PROXY_HOST=http://127.0.0.1:7000
bunker6.tt_INTERCEPTED_ERROR_CODES=400 404 405 413 429 500 501 502 503 504
```

### Relevant log output

```shell
nothing
```

### BunkerWeb version

1.5.2

### What integration are you using?

Linux

### Linux distribution (if applicable)

Fedora 38 (updated to the latest)

### Removed private data

- [X] I have removed all private data from the configuration file and the logs

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TheophileDiot** [comment]
Hi @weizhuangzhi, I couldn't manage to reproduce your error. Is it possible that you give us more information about the steps to reproduce your error ?

**Comment by weizhuangzhi** [comment]
Could it be related to url accessibility in Global_config's DNSBL list?

Sometimes these URLs cannot be accessed in an intranet environment, and Plugins sometimes displays: PLUGINS ERRORS 1

Can it be reproduced if the URL in the DNSBL list is set to a non-existent URL?
If this affects whether the configuration can be saved, ignore this accessibility issue. I have tested it many times and it seems that it cannot be reproduced every time. If a problem occurs and it seems that the program has interrupted execution, delete the configuration directory of the site and execute this process. But the re-creation process is not executed.

**Comment by weizhuangzhi** [comment]
Reinstalled and tested again.

```
sudo dnf update -y
sudo dnf install -y nginx-1.24.0
curl -s https://packagecloud.io/install/repositories/bunkerity/bunkerweb/script.rpm.sh | \
sed 's/yum install -y pygpgme --disablerepo='\''bunkerity_bunkerweb'\''/yum install -y python-gnupg/g' | \
sed 's/pypgpme_check=`rpm -qa | grep -qw pygpgme`/python-gnupg_check=`rpm -qa | grep -qw python-gnupg`/g' | sudo bash && \
sudo dnf makecache && \
sudo dnf install -y bunkerweb-1.5.2

sudo tee /etc/bunkerweb/ui.env >/dev/null <<EOF
ADMIN_USERNAME=administrator
ADMIN_PASSWORD=*************
EOF

sudo tee /etc/bunkerweb/variables.env >/dev/null <<EOF
DNS_RESOLVERS=8.8.8.8 8.8.4.4
HTTP_PORT=80
HTTPS_PORT=443
API_LISTEN_IP=127.0.0.1
API_HTTP_PORT=7001
SERVER_NAME=bunker6.tt
MULTISITE=yes

bunker6.tt_USE_UI=yes
bunker6.tt_USE_REVERSE_PROXY=yes
bunker6.tt_REVERSE_PROXY_URL=/manage
bunker6.tt_REVERSE_PROXY_HOST=http://127.0.0.1:7000
bunker6.tt_INTERCEPTED_ERROR_CODES=400 404 405 413 429 500 501 502 503 504
EOF

# restart service
sudo systemctl restart bunkerweb
sudo systemctl status bunkerweb --no-pager
sudo systemctl restart bunkerweb-ui
sudo systemctl status bunkerweb-ui --no-pager

# open firewall web ports
sudo firewall-cmd --permanent --add-service=http
sudo firewall-cmd --permanent --add-service=https
sudo firewall-cmd --reload
```

Visit `http://bunker6.tt/manage/` to enter the Web UI. In order to simulate the situation where the DNSBL URL is inaccessible, set the Global configs DNSBL list to: `dnsbl.unknown.net`, and then save it.

To avoid the impact of caching, etc., run the following command:
sudo systemctl restart bunkerweb
sudo systemctl restart bunkerweb-ui

Enter the Web UI, create a service, set the Server name to: `mysite.net`, save other settings without setting them, and view the files in the /etc/nginx directory:
![image](https://github.com/bunkerity/bunkerweb/assets/4264162/5a608ac7-f82c-4615-b3b9-891be9476f7c)

Enter the Web UI, edit the mysite.net service, save it directly without modifying any settings, and view the files in the /etc/nginx directory:
![image](https://github.com/bunkerity/bunkerweb/assets/4264162/82e74935-b3e4-42ab-9092-face3fc75709)

It is not a problem of slow execution of the background program, because after waiting for a long time, there is still no mysite.net directory generated.

**Comment by TheophileDiot** [comment]
Hi @weizhuangzhi, we'll shortly push a new `testing` release for Linux packages, could you test if the issue still occurs with it ?

**Comment by weizhuangzhi** [comment]
Okay, I'll test it as soon as it's released.

**Comment by weizhuangzhi** [comment]
Comparison of nginx configuration directories when generating files successfully and unsuccessfully:
![image](https://github.com/bunkerity/bunkerweb/assets/4264162/7ff9c6fd-e15d-4dd4-9710-3ba828e0a061)

http.conf : There is one line of difference.
![image](https://github.com/bunkerity/bunkerweb/assets/4264162/b473e84f-6dc1-4b7c-a572-214bafb1ed14)

variables.env : All variable definitions starting with "mysite.net_" are missing.
![image](https://github.com/bunkerity/bunkerweb/assets/4264162/9e62f9fb-d816-4779-b51c-c2e41841d30b)

**Comment by TheophileDiot** [comment]
Interesting, i'll try this again when I have the time

**Comment by TheophileDiot** [comment]
Hi @weizhuangzhi a few fixes and optimisation have been done since yesterday. If you have the time, you can test the latests changes with the `dev` tag.
This commit might have fixed your issue : https://github.com/bunkerity/bunkerweb/commit/48096d711cb4adb061dbeb3c9c91018b2f18496d

**Comment by weizhuangzhi** [comment]
@TheophileDiot Thank you, this problem no longer exists in the dev branch.
