### ISSUE TITLE
[FEATURE] Add the possibility to upload custom certificates through the UI

### ISSUE THREAD

**Issue by 0FiRE0** [bunkerity/bunkerweb#642]
### What's needed and why?

Currently, in the "Self-Signed Certificate" configurations from the UI, there is one option to generate a certificate (as per the screenshot below).

But there is no option to upload a certificate/key by the user, as in some cases the user might have a pre-generated signed certificate, either self-signed or signed by a custom CA or so.

Please add the option to upload a certificate, key, and certificate chain (optional).

<img width="1390" alt="image" src="https://github.com/bunkerity/bunkerweb/assets/19993814/726fd898-e5fd-45a1-b361-aa3010ca717b">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TheophileDiot** [comment]
Hi @0FiRE0, thank you for opening this feature request. Are you referring to the already existing custom certificate feature ? https://docs.bunkerweb.io/testing/settings/#custom-https-certificate

**Comment by 0FiRE0** [comment]
Hi @TheophileDiot ,
Thank you for your swift feedback.
Correct, I am referring to the custom certificate, as currently it is only configurable through the config files, but missing in the Web UI.

**Comment by 0FiRE0** [comment]
Also as an enhancement to the existing custom certificate configs in the link  https://docs.bunkerweb.io/testing/settings/#custom-https-certificate

Currently, it does not support including the intermediate certificate chain (an optional attribute), where it is being used in the case the custom certificate does not include the full chain to the CA and it needs to be included separately.

**Comment by fl0ppy-d1sk** [comment]
> Also as an enhancement to the existing custom certificate configs in the link https://docs.bunkerweb.io/testing/settings/#custom-https-certificate
> 
> Currently, it does not support including the intermediate certificate chain (an optional attribute), where it is being used in the case the custom certificate does not include the full chain to the CA and it needs to be included separately.

You will need to create a bundle file instead of just using the end-user certificate file in `CUSTOM_SSL_CERT`.

More info here : https://nginx.org/en/docs/http/configuring_https_servers.html#chains

**Comment by 0FiRE0** [comment]
Thank you @fl0ppy-d1sk for your feedback.
