### ISSUE TITLE
[FEATURE] Is sync-xhr 'none' appropriate as default value in Feature-Policy?

### ISSUE THREAD

**Issue by weizhuangzhi** [bunkerity/bunkerweb#646]
### What's needed and why?

Testing the website found that many pages had js errors:
Uncaught DOMException: Failed to execute 'send' on 'XMLHttpRequest': Failed to load '***'.

Later it was discovered that this problem was caused by sync-xhr 'none' in the header Feature-Policy.

I don’t quite understand the function of this setting, so I quoted the instructions online:
> The HTTP Feature-Policy header sync-xhr directive controls whether the current document is allowed to make synchronous XMLHttpRequest requests.

When I measured it, it seemed that an error would occur whenever there was an ajax request, so I would like to ask if sync-xhr 'none' in Feature-Policy is appropriate as the default value?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fl0ppy-d1sk** [comment]
Hello @weizhuangzhi,

Thanks for your feedback.

According to [documentation](https://udn.realityripple.com/docs/Web/HTTP/Headers/Feature-Policy/sync-xhr), `sync-xhr` only allows/denies **synchronous requests**.

By default, ajax requests are **asynchronous**, developers need to explicitly add a `false` argument to make **synchronous** request. Quoting [Mozilla documentation](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/Synchronous_and_Asynchronous_Requests) : 

> Synchronous XHR requests often cause hangs on the web, especially with poor network conditions or when the remote server is slow to respond. Synchronous XHR is now deprecated and should be avoided in favor of asynchronous requests.

IMHO, we should keep the current `none` value. What do you think ?

**Comment by weizhuangzhi** [comment]
thank you for your reply.

It seems that if you want to retain sync-xhr "none", you need to modify the website code to comply with this header setting.
