### ISSUE TITLE
[FEATURE] HTTP3 Support

### ISSUE THREAD

**Issue by dalso0418** [bunkerity/bunkerweb#678]
### What's needed and why?

Hello.
From version 1.25 of nginx mainline, I understand that ngx_http_v3 module with HTTP/3 protocol has been added.

Could you support http3 on the bunkerweb??

Thank you for the fantastic project.
from Korean users

*This content has been translated through a translator, so please understand even if there are mistranslations.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fl0ppy-d1sk** [comment]
Hello @dalso0418,

Your translation is perfect don't worry. Hello to all Korean users 🇰🇷 !

HTTP/3 support would be awesome, you're absolutely right.

But we have at least two things to consider.

BunkerWeb only supports stable version of nginx which is 1.24.X at the moment.
We can support both stable and mainline nginx versions and two flavors of BW (`bunkerweb` and `bunkerweb-mainline` for example) or simply wait for next 1.26.X stable version.

Under the hood, BW uses the [lua-nginx-module](https://github.com/openresty/lua-nginx-module) and we need to check if HTTP/3 is supported by the library (and other LUA dependencies).

IMO, we should wait until 1.26.X is released and then makes sure that LUA deps support it.

**Comment by dalso0418** [comment]
Thank you for your response.
I'm looking forward to it in the future

Have a great day!

**Comment by eddyJK** [comment]
Hello Bunkerweb Team!

Any update on the http3 feature with the 1.26.X release on 2024-04-23?

I am so curious about that particular feature.

Kind redgards

**Comment by TheophileDiot** [comment]
Hi @eddyJK, thank you for your comment. We'll have a look into it and let you know. 😄

**Comment by cocoonkid** [comment]
1.5.8 includes experimental support.
