### ISSUE TITLE
[BUG]  Issue Turning Off headering on webGUI

### ISSUE THREAD

**Issue by killmasta93** [bunkerity/bunkerweb#693]
### What happened?

Trying to test out a website to disable all headers

### How to reproduce?

First i did this to disable 

![image](https://github.com/bunkerity/bunkerweb/assets/13953629/fc83f8df-8ebb-45d6-a0f8-8ef2c66a96e7)

after i click save it reloads the config again 

![image](https://github.com/bunkerity/bunkerweb/assets/13953629/da17be2e-d417-4d72-a968-f9a4a5430831)

### Relevant log output

```shell
issue on the WebGUI
```

### BunkerWeb version

1.5.2

### What integration are you using?

Docker

### Linux distribution (if applicable)

ubuntu 20.04

### Removed private data

- [X] I have removed all private data from the configuration file and the logs

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TheophileDiot** [comment]
Hi @killmasta93, I'm trying to figure out what you're trying to do, could you develop a bit more on this please ?

**Comment by killmasta93** [comment]
Hi @TheophileDiot  thank you so much for the reply, on the WebGUI lets say i put x-frame options in blank and when i save it it goes back to same origin, wanted to test out first without any headers to test out a custom app before applying the security. 
Thank you

**Comment by TheophileDiot** [comment]
Hi @killmasta93, we also have the `KEEP_UPSTREAM_HEADERS` setting if you're interested in keeping specific headers sent from the reverseproxied service (if you set the value to `*`, it will stop overriding every headers that BunkerWeb already overrides, except those who are removed for security reasons).
If you want to remove specific headers I would recommend using the `REMOVE_HEADERS` setting, you can find them all here : https://docs.bunkerweb.io/1.5.2/settings/#headers

**Comment by killmasta93** [comment]
hi @TheophileDiot Thank you so much for the reply,

**Comment by TheophileDiot** [comment]
Hi @killmasta93, let's keep this open until the next release if that's okay with you, in case someone stumble on the same issue 😄

**Comment by fl0ppy-d1sk** [comment]
Hello @killmasta93,

It should be fixed in the last 1.5.3 release. Don't hesitate to open a new issue if needed.
