### ISSUE TITLE
[BUG]  issue to whitelist on webGUI

### ISSUE THREAD

**Issue by killmasta93** [bunkerity/bunkerweb#716]
### What happened?

Hi,
It does not let me save the whitelist 
![image](https://github.com/bunkerity/bunkerweb/assets/13953629/43d4e4b6-eab0-4dd0-b067-86a66e3882da)

only lets me adding whitelist URL 

![image](https://github.com/bunkerity/bunkerweb/assets/13953629/e2be1c46-09eb-4421-ac72-c04f2e2eb1c0)

### How to reproduce?

Added the IP with the correct segment 

### Relevant log output

```shell
Error showing on the picture
```

### BunkerWeb version

1.5.2

### What integration are you using?

Docker

### Removed private data

- [X] I have removed all private data from the configuration file and the logs

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TheophileDiot** [comment]
Hi @killmasta93, thank you for opening this issue. i'll investigate on this and let you know !

**Comment by TheophileDiot** [comment]
On the web UI for know, multisite settings can only be configured in the `services` page. The `Whitelist IP/network URLs` only accepts URLs and not individual IP/network.

**Comment by killmasta93** [comment]
hi @TheophileDiot Thank you so much for the reply, so the issue im having is that using uptime kuma to monitor the sites, and every now and then bunkerweb blocks it, if i would add a A record to the IP that monitors the websites would i add the A record in the  Whitelist IP/network URLs? would that work or would i need to go to every site on bunkerweb add the IP?

Thank you

**Comment by TheophileDiot** [comment]
Hi @killmasta93, what you can do i configure it manually as for now we can't (yet) configure multisite settings for every service at the same in the web UI. Feel free to check out this part of the doc for the manual configuration 😁
https://docs.bunkerweb.io/1.5.2/concepts/#multisite-mode

**Comment by fl0ppy-d1sk** [comment]
Hello @killmasta93,

Whilelist IP/network URLs should contain remote whitelists (text files) that BW will download regularly.

Here is what you can do : 
- Create a basic web server that serves the whitelist file and set the address in the whitelist IP/network URLs
- Use manual configuration (not using the UI) to override the whitelist IP/network (raw values) : https://docs.bunkerweb.io/latest/quickstart-guide/#custom-configurations
- Configure each service to whitelist IP/network (raw values)

On a side note, setting default multisite value for all services is a nice feature, I think we should add the feature in the v2 (cc @TheophileDiot @syrk4web).

Don't hesitate to open a new issue if needed.
