### ISSUE TITLE
[BUG] NGINX Crashing with error - shdict.lua:490: attempt to compare boolean with number

### ISSUE THREAD

**Issue by ebs-hkotrolos** [bunkerity/bunkerweb#743]
### What happened?

Setting up a new service for Plex using the UI. While updating settings to finalise my reverse proxy settings, BunkerWeb restarted by all services (including UI via DNS or IP) became unreachable.

Looking at running services, BunkerWeb and BunkerWeb-UI are in a running state, but the NGINX service is stuck in a failed state.

I noticed in the start.sh log for my VM was throwing an error for NGINX saying it cannot reach the upstream HOST

```
nginx: [emerg]
invalid host in upstream "http://192.168.103.200:32400" in /etc/nginx/stream.conf
47.993415] start.sh[7878]: [2023-11-01 22:10:50] - GENERATOR
48.002218] start.sh [7878]: [2023-11-01 22:10:501 - GENERATOR
Error while reloading nginx
```

Can confirm host is reachable from bunkerWeb VM using CURL

```
curl http://192.168.103.200:32400
<html><head><script>window.location = window.location.href.match(/(^.+\/)[^\/]*$/)[1] + 'web/index.html';</script><title>Unauthorized</title></head><body><h1>401 Unauthorized</h1></body>
```

### How to reproduce?

Configuring a service in BunkerWeb-UI, and updated following settings:

- HTTP to STREAM
- LetsEncrypt SSL
- HTTP->HTTPS

Saved config and BunkerWeb restarted, all services (including UI via DNS or IP) unreachable.

### Relevant log output

```shell
nginx: [error] init_by_lua error: /usr/share/bunkerweb/deps/lib/lua/resty/core/shdict.lua:490: attempt to compare boolean with number
Nov 01 21:53:09 bunkerweb-prod nginx[83744]: stack traceback:
Nov 01 21:53:09 bunkerweb-prod nginx[83744]:         /usr/share/bunkerweb/deps/lib/lua/resty/core/shdict.lua:490: in function 'set'
Nov 01 21:53:09 bunkerweb-prod nginx[83744]:         init_by_lua:38: in main chunk
Nov 01 21:53:09  bunkerweb-prod systemd[1]: nginx.service: Control process exited, code=exited, status=1/FAILURE
```

### BunkerWeb version

1.5.3

### What integration are you using?

Linux

### Linux distribution (if applicable)

Ubuntu Server 22.04

### Removed private data

- [X] I have removed all private data from the configuration file and the logs

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TheophileDiot** [comment]
Hi @ebs-hkotrolos, thank you for opening this issue. We're currently investigating the issue

**Comment by ebs-hkotrolos** [comment]
Hi @TheophileDiot, thanks for the update. I did some testing to investigate also.

I accessed the sqlite3 file in /var/lib/bunkerweb and updated the _bw_services_setting_ row for _server_type_ from STREAM to HTTP.

I restarted Bunkerweb and everything started up with no dramas.

I'll update it back to STREAM both in the UI and directly in DB and see if it re-creates the problem.

**Comment by TheophileDiot** [comment]
Hi @ebs-hkotrolos, did you manage to reproduce the bug ?

**Comment by fl0ppy-d1sk** [comment]
Hello @ebs-hkotrolos,

Fix should be available on the testing version, more info here : https://docs.bunkerweb.io/testing/

Don't hesitate to test it and tell us if everything is ok !
