### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by rcinformatica1** [bunkerity/bunkerweb#748]
### What happened?

O meu, finaliza tudo corretamente, só que dá erro ao abrir o site,
erro no servidor, o que posso fazer para solucionar o problema,

no domínio principal, https://nomedosite.com/ , https://auth.nomedosite.com/, https://wg.nomedosite.com/ , aparece assim

Bad Gateway 502
The request was not completed. The server received an invalid response from the upstream server.

o que pode ser isso, alguém pode me ajudar a resolver o problema por favor....

ao finalizar consigo logar normal no servidor, utilizando o parâmetro normal,

ssh -p 22 usuário@númerodoseuip -i ~/.ssh/path-to-your-key

como eu faço para solucionar esse erro ao abrir a página
https://wg.nomedosite.com/
![serv](https://github.com/bunkerity/bunkerweb/assets/117770606/402c6fa0-c58f-49b2-bf00-5c302fe23503)

### How to reproduce?

...

### Configuration file(s) (yaml or .env)

```YAML
...
```

### Relevant log output

```shell
...
```

### BunkerWeb version

1.5.3

### What integration are you using?

Linux

### Linux distribution (if applicable)

Debian 11 | kinghost

### Removed private data

- [X] I have removed all private data from the configuration file and the logs

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TheophileDiot** [comment]
Hi @rcinformatica1, thank you for opening this issue. Could you translate it in English as this is the primary spoken language of this project ? Thank you.

**Comment by TheophileDiot** [comment]
As there are no apparent activity with this issue I'm gonna close it. Feel free to open it to give us more information, thank you.
