### ISSUE TITLE
[FEATURE] Official support for REHL 9?

### ISSUE THREAD

**Issue by nodew** [bunkerity/bunkerweb#749]
### What's needed and why?

REHL 9 has been released over 1 year, so is it possible to build an official release for this OS?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cocoonkid** [comment]
I run the docker relase on RHEL9. Does this not suffice?

**Comment by kovacs-andras** [comment]
What would be your use case? I don't see the point either.
The bunkerweb container image is based on Alpine. The base Alpine image is 7.35 MB while the whole Bunkerweb image is 188 MB.
The latest Red Hat Universal Base Image 9 is 219 MB by itself...

**Comment by fl0ppy-d1sk** [comment]
Hello @nodew,

RHEL9 is available on the testing version, more info here : https://docs.bunkerweb.io/testing/

Don't hesitate to test it and tell us if everything is ok !

**Comment by fl0ppy-d1sk** [comment]
Hello @nodew,

RHEL 9 is now supported since the 1.5.6 version ! Thanks for your feedback.
