### ISSUE TITLE
[DOC] Country security feature

### ISSUE THREAD

**Issue by AntoOnline** [bunkerity/bunkerweb#754]
### Description

I configured the BLACKLIST_COUNTRY and WHITELIST_COUNTRY for some sites as per below:

Setting | Description
BLACKLIST_COUNTRY |   List of 2 letters country code to blacklist.
WHITELIST_COUNTRY |   List of 2 letters country code to whitelist.

As a new user of the feature, I then assumed the country code could be lowercase. As per my observation, this assumption was wrong (unless I did something wrong). 

This issue persists in the configuration tool as well as:
- https://docs.bunkerweb.io/latest/security-tuning/#country
- https://docs.bunkerweb.io/latest/settings/#country

In addition to this, it leaves me wondering if I could ban multiple countries using a space-separated list of country codes. I have not tested this but assume that you can?

### Proposed solution (optional)

Using both country blacklist and whitelist at the same time makes no sense. If you do, please note that only the whitelist will be executed.

The country code for blacklist and whitelist must be uppercase, Eg. AU. 

You can add multiple country codes using a space-separated list, Eg. US AU UK.

For a full list of the supported ISO 3166-1 alpha-2  visit: [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TheophileDiot** [comment]
Hi @AntoOnline, thank you for your feature request. Indeed the country codes have to be uppercase only (like in the mmdb files)

**Comment by fl0ppy-d1sk** [comment]
Hello @AntoOnline,

This is fixed in the documentation of 1.5.5. Thanks !
