### ISSUE TITLE
[FEATURE] Add option to force redirect to https when inbound request scheme is http.

### ISSUE THREAD

**Issue by nodew** [bunkerity/bunkerweb#755]
### What's needed and why?

Need force client to communicate with the server by https.

### Implementations ideas (optional)

When the option is enabled, inject the following lines to the configuration.
```
server {
    ...
    if ($host = www.example.com) {
        return 301 https://$host$request_uri;
    }
    ...
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TheophileDiot** [comment]
Hi @nodew, there is already a setting for this, it's the `REDIRECT_HTTP_TO_HTTPS` setting, when set to yes it redirects all HTTP requests to HTTPS.
https://docs.bunkerweb.io/latest/settings/#miscellaneous
