### ISSUE TITLE
[BUG]   using an underscore as server_name in the env vars fails LE and all sites. 

### ISSUE THREAD

**Issue by cocoonkid** [bunkerity/bunkerweb#757]
### What happened?

[BUG]   using an underscore as server_name in the env vars fails LE and all sites. 

Underscores can actually be used in domain names. But it is surely not best practive.

Anyways, I suggest Bunkerweb prints a warning in that case. 

Cost me 2 hours to debug this :)

### How to reproduce?

Try using a subdomain with underscore like :  nginx_mail.<FQDN>

### Configuration file(s) (yaml or .env)

```YAML
SERVER_NAME="nginx_mail.<domain>.com"
```

### Relevant log output

```shell
None
```

### BunkerWeb version

1.5.3

### What integration are you using?

Docker

### Linux distribution (if applicable)

Arch

### Removed private data

- [X] I have removed all private data from the configuration file and the logs

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TheophileDiot** [comment]
Hi @cocoonkid, there actually are logs from Let's Encrypt in the scheduler describing the issue:
e.g.
```
Unable to register an account with ACME server. The ACME server believes contact@www.example_test.com is an invalid email address. Please ensure it is a valid email and attempt registration again.
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/bunkerweb/letsencrypt.log or re-run Certbot with -v for more details.
```
or
```
An unexpected error occurred:
Error creating new order :: Cannot issue for "www.example_test.com": Domain name contains an invalid character
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/bunkerweb/letsencrypt.log or re-run Certbot with -v for more details.
```

Looks like this isn't an issue (bug) with BunkerWeb but more likely one with Let's Encrypt (or certbot) itself.

**Comment by cocoonkid** [comment]
I see. Very interesting.  Thanks for investigating.

**Comment by fl0ppy-d1sk** [comment]
Hello @cocoonkid,

v1.5.5 now includes a fallback mechanism in case a certificate fail. Feel free to test it and give us some feedbacks.
