### ISSUE TITLE
[FEATURE] support uwsgi_params in reverse proxy default configuration

### ISSUE THREAD

**Issue by adrienthiery** [bunkerity/bunkerweb#795]
### What's needed and why?

👋 

I just switched my app from [gunicorn](https://gunicorn.org/) to [uwsgi](https://uwsgi-docs.readthedocs.io/en/latest/) (python web servers) and was using bunkerweb in front of my app, but I can't seem to find how to manage the config with uwsgi, which needs an extra instruction in the `location` block : 
```
include uwsgi_params;
```
I see that bunkerweb (as nginx) supports `uwsgi` but the current reverse proxy options don't allow us to add this instruction (or I didn't find how)

### Implementations ideas (optional)

Add a `REVERSE_PROXY_INCLUDE` env variable to allow us to include what we want in https://github.com/bunkerity/bunkerweb/blob/588d04c7de66f550bccdc19d7ee03d075aa590e1/src/common/core/reverseproxy/confs/server-http/reverse-proxy.conf#L42 ?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TheophileDiot** [comment]
Hi @adrienthiery, thank you for opening this feature request. Could you develop a bit more about what's needed ? Does the automatic `etag off;` directive in the reverse proxy bothers the `uwsgi` ? Also about the setting, will it be an automatic include of different directives or just the `uwsgi_params` one ?

**Comment by adrienthiery** [comment]
Hi @TheophileDiot ,

Sorry, my request is not related to `etag` at all, but that extract was to link to the config related to the request 😅 

To work with `uwsgi`, we need to add an `include uwsgi_params` , and there for sure are other cases where you just need to include something (for example, I had some trouble with CORS allowing multiple subdomains at some point, and I figured I could have created a template and include it in here, which would have been neat)

So, the initial idea would be to allow a custom `include` statement (for example for the `uwsgi_params`) which could already help anyone needing a proxy using `uwsgi`, and then further down the line maybe some more expandable configuration of includes?

I hope this helps clarify my thoughts!

**Comment by TheophileDiot** [comment]
Hi @adrienthiery, I'm getting back on this issue. I'll see what I can do.

**Comment by TheophileDiot** [comment]
Hi @adrienthiery, this setting should respond to your need and more :smile:

**Comment by adrienthiery** [comment]
Nice! Looks good :)
