### ISSUE TITLE
[BUG] scheduler error _getdefaultlocale

### ISSUE THREAD

**Issue by sebstyle** [bunkerity/bunkerweb#862]
### What happened?

[2024-01-12 21:17:29] - ENTRYPOINT - ℹ️  - Executing scheduler ...

Traceback (most recent call last):

  File "/usr/share/bunkerweb/scheduler/main.py", line 15, in <module>

    from subprocess import run as subprocess_run, DEVNULL, STDOUT, PIPE

  File "/usr/local/lib/python3.12/subprocess.py", line 46, in <module>

    import locale

  File "/usr/local/lib/python3.12/locale.py", line 552

    def _getdefaultlocale(envvars=('LC_ALL', 'LC_CTYPE', 'LANG', gLANGUAGE')):

                                                                          ^

SyntaxError: unterminated string literal (detected at line 552)

[2024-01-12 21:17:29] - ENTRYPOINT - ℹ️  - Scheduler stopped

### How to reproduce?

Configuration taken from https://docs.bunkerweb.io/latest/web-ui/#advanced-installation

### BunkerWeb version

1.5.5

### What integration are you using?

Docker

### Linux distribution (if applicable)

Debian 12

### Removed private data

- [X] I have removed all private data from the configuration file and the logs

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TheophileDiot** [comment]
Hi @sebstyle, thank you for opening this issue. Did you build it from the github project or did you use the version 1.5.5 like in the docker-compose file ?

**Comment by sebstyle** [comment]
No build.
Like in the docker-compose file.

**Comment by TheophileDiot** [comment]
Hi, sadly I couldn't reproduce your issue but it looks like this is linked with debian locales configuration, could you try running the following commands and see if this fixes your issue ?

**Comment by sebstyle** [comment]
Related to podman. I guess I should've mentioned that in the report. My bad. It runs fine on docker.
1.5.5 looks great keep up the good work.
But if i may suggest an improvement to the UI; add an **about** page; the social media links and the ticker tape are a bit much.

**Comment by TheophileDiot** [comment]
Hi @sebstyle, thank you for investigating this issue :pray:.
Also thank you for the UI suggestion, we'll have a look at your idea and let you know :smile:
